import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
PAGE = "D:/Synexiun/1-SynexFund/HedgeCalc/FXDemo/frontend/src/app/input/page.tsx"
with open(PAGE, "r", encoding="utf-8") as file: content = file.read()
print(f"Loaded: {len(content)} chars")
q=chr(39); nl=chr(10); bt=chr(96); dq=chr(34)
U2500=chr(0x2500); U25B2=chr(0x25b2); U25BC=chr(0x25bc); U25C4=chr(0x25c4); U25BA=chr(0x25ba); LB=chr(123); RB=chr(125); U00B7=chr(0x00b7)
L=[]; l=L.append
l("{/* Form grid " + chr(8212) + " Bloomberg terminal style: 2-row, 4-col */}")
l("                {(() => {")
l("                  function fmtAmt(val: number): string {")
l("                    if (!val || isNaN(val)) return "+ dq + dq + ";")
l(f"                    return new Intl.NumberFormat({q}en-US{q}).format(val);")
l("                  }")
l("                  function handleAmountChange(raw: string) {")
l(f"                    const stripped = raw.replace(/[^0-9.]/g, {q}{q});")
l("                    setAmountDisplay(stripped);")
l("                    setInlineField("+ dq + "amount" + dq + ", parseFloat(stripped) || 0);")
l("                  }")
l("                  function handleAmountFocus() {")
l(f"                    setFocusedField({q}amount{q});")
l("                    setAmountDisplay(inlineForm.amount ? String(inlineForm.amount) : "+ dq + dq + ");")
l("                  }")
l("                  function handleAmountBlur() {")
l("                    setFocusedField(null);")
l(f"                    touchInline({q}amount{q});")
l("                    setAmountDisplay(fmtAmt(inlineForm.amount));")
l("                  }")
l("                  function fb(field: string, hasErr: boolean): string {")
l(f"                    if (hasErr) return {bt}2px solid ${LB}S.red{RB}{bt};")
l(f"                    if (focusedField === field) return {bt}2px solid ${LB}S.cyan{RB}{bt};")
l(f"                    return {bt}1px solid ${LB}S.borderSoft{RB}{bt};")
l("                  }")
l("                  const errRecordId = inlineTouched.record_id && !inlineForm.record_id.trim()")
l(f"                    ? {q}Required{q} : inlineTouched.record_id && inlineIdDuplicate ? {q}ID exists{q} : null;")
l(f"                  const errEntity = inlineTouched.entity && !inlineForm.entity.trim() ? {q}Required{q} : null;")
l(f"                  const errAmount = inlineTouched.amount && !(inlineForm.amount > 0) ? {q}Must be > 0{q} : null;")
l(f"                  const errDate   = inlineTouched.value_date && !inlineForm.value_date ? {q}Required{q} : null;")
l("                  const fieldCell: React.CSSProperties = {")
l(f"                    background: S.bgPanel, padding: {q}10px 14px{q},")
l(f"                    display: {q}flex{q}, flexDirection: {q}column{q}, gap: 5,")
l("                  };")
l("                  const labelStyle: React.CSSProperties = {")
l(f"                    fontFamily: S.fontMono, fontSize: {q}0.625rem{q},")
l(f"                    letterSpacing: {q}0.12em{q}, color: S.textTertiary,")
l(f"                    textTransform: {q}uppercase{q},")
l(f"                    display: {q}flex{q}, alignItems: {q}center{q}, gap: 6,")
l("                  };")
l("                  const inputStyle: React.CSSProperties = {")
l(f"                    fontFamily: S.fontMono, fontSize: {q}0.875rem{q},")
l(f"                    background: {q}transparent{q}, border: {q}none{q},")
l(f"                    color: S.textPrimary, padding: {q}3px 0{q},")
l(f"                    outline: {q}none{q}, width: {q}100%{q},")
l("                  };")
l("")
l("                  return (")
l("                    <>")
l("                    {/* Row 1: Identifiers */}")
l(f"                    <div style={LB}{LB} display: {q}grid{q}, gridTemplateColumns: {q}repeat(4, 1fr){q}, gap: 1, background: S.border {RB}{RB}>")
l("                      {/* RECORD ID */}")
l("                      <div style={fieldCell}>")
l("                        <label style={{ ...labelStyle, color: errRecordId ? S.red : S.textTertiary }}>")
l(f"                          RECORD ID {LB}errRecordId && <span style={LB}{LB} color: S.red, fontWeight: 400, letterSpacing: {q}0.04em{q} {RB}{RB}> {chr(8212)} {LB}errRecordId{RB}</span>{RB}")
l("                        </label>")
l(f"                        <input type={dq}text{dq} value={LB}inlineForm.record_id{RB}")
l(f"                          onChange={LB}e => setInlineField({q}record_id{q}, e.target.value){RB}")
l(f"                          onFocus={LB}() => setFocusedField({q}record_id{q}){RB}")
l(f"                          onBlur={LB}() => {{ setFocusedField(null); touchInline({q}record_id{q}); }}{RB}")
l(f"                          placeholder={dq}e.g. TXN-001{dq}")
l(f"                          style={LB}{LB} ...inputStyle, borderBottom: fb({q}record_id{q}, !!errRecordId) {RB}{RB}")
l("                        />")
l("                      </div>")
l("                      {/* ENTITY */}")
l("                      <div style={fieldCell}>")
l("                        <label style={{ ...labelStyle, color: errEntity ? S.red : S.textTertiary }}>")
l(f"                          ENTITY {LB}errEntity && <span style={LB}{LB} color: S.red, fontWeight: 400, letterSpacing: {q}0.04em{q} {RB}{RB}> {chr(8212)} {LB}errEntity{RB}</span>{RB}")
l("                        </label>")
l(f"                        <input type={dq}text{dq} value={LB}inlineForm.entity{RB}")
l(f"                          onChange={LB}e => setInlineField({q}entity{q}, e.target.value){RB}")
l(f"                          onFocus={LB}() => setFocusedField({q}entity{q}){RB}")
l(f"                          onBlur={LB}() => {{ setFocusedField(null); touchInline({q}entity{q}); }}{RB}")
l(f"                          placeholder={dq}e.g. Acme Corp{dq}")
l(f"                          style={LB}{LB} ...inputStyle, borderBottom: fb({q}entity{q}, !!errEntity) {RB}{RB}")
l("                        />")
l("                      </div>")
l("                      {/* FLOW TYPE */}")
l("                      <div style={fieldCell}>")
l("                        <label style={labelStyle}>FLOW TYPE</label>")
l(f"                        <div style={LB}{LB} display: {q}flex{q}, alignItems: {q}center{q}, gap: 8, borderBottom: fb({q}type{q}, false), paddingBottom: 3 {RB}{RB}>")
l("                          <span style={{")
l(f"                            fontFamily: S.fontMono, fontSize: {q}0.5625rem{q}, fontWeight: 700,")
l(f"                            padding: {q}1px 5px{q}, borderRadius: 2, letterSpacing: {q}0.06em{q},")
l(f"                            background: inlineForm.type === {q}AP{q}")
l(f"                              ? {bt}color-mix(in srgb, ${LB}S.red{RB} 12%, transparent){bt}")
l(f"                              : {bt}color-mix(in srgb, ${LB}S.green{RB} 12%, transparent){bt},")
l(f"                            color: inlineForm.type === {q}AP{q} ? S.red : S.green,")
l("                          }}>{inlineForm.type}</span>")
l("                          <select")
l(f"                            value={LB}inlineForm.type{RB}")
l(f"                            onChange={LB}e => setInlineField({q}type{q}, e.target.value as TradeRow[{q}type{q}]){RB}")
l(f"                            onFocus={LB}() => setFocusedField({q}type{q}){RB}")
l("                            onBlur={() => setFocusedField(null)}")
l(f"                            style={LB}{LB} ...inputStyle, flex: 1, cursor: {q}pointer{q}, borderBottom: {q}none{q}, padding: {q}2px 0{q}, fontSize: {q}0.75rem{q} {RB}{RB}")
l("                          >")
l(f"                            <option value={dq}AP{dq}>AP {chr(8212)} Accounts Payable</option>")
l(f"                            <option value={dq}AR{dq}>AR {chr(8212)} Accounts Receivable</option>")
l("                          </select>")
l("                        </div>")
l("                      </div>")
l("                      {/* CURRENCY */}")
l("                      <div style={fieldCell}>")
l("                        <label style={labelStyle}>CURRENCY</label>")
l("                        <select")
l(f"                          value={LB}inlineForm.currency{RB}")
l(f"                          onChange={LB}e => setInlineField({q}currency{q}, e.target.value as FuturesCurrency){RB}")
l(f"                          onFocus={LB}() => setFocusedField({q}currency{q}){RB}")
l("                          onBlur={() => setFocusedField(null)}")
l(f"                          style={LB}{LB} ...inputStyle, cursor: {q}pointer{q}, borderBottom: fb({q}currency{q}, false) {RB}{RB}")
l("                        >")
l("                          {FUTURES_CURRENCY_LIST.map(c => (")
l(f"                            <option key={LB}c.code{RB} value={LB}c.code{RB}>{LB}c.code{RB} {chr(8212)} {LB}c.name{RB}</option>")
l("                          ))}")
l("                        </select>")
l("                      </div>")
l("                    </div>")
l("")
l("                    {/* Row 2: Execution Details */}")
l(f"                    <div style={LB}{LB} display: {q}grid{q}, gridTemplateColumns: {q}repeat(4, 1fr){q}, gap: 1, background: S.border {RB}{RB}>")
l("                      {/* AMOUNT */}")
l("                      <div style={fieldCell}>")
l("                        <label style={{ ...labelStyle, color: errAmount ? S.red : S.textTertiary }}>")
l(f"                          AMOUNT ({LB}inlineForm.currency{RB}) {LB}errAmount && <span style={LB}{LB} color: S.red, fontWeight: 400, letterSpacing: {q}0.04em{q} {RB}{RB}> {chr(8212)} {LB}errAmount{RB}</span>{RB}")
l("                        </label>")
l(f"                        <div style={LB}{LB} display: {q}flex{q}, alignItems: {q}center{q}, borderBottom: fb({q}amount{q}, !!errAmount), paddingBottom: 3 {RB}{RB}>")
l(f"                          <span style={LB}{LB} fontFamily: S.fontMono, fontSize: {q}0.75rem{q}, color: S.textTertiary, marginRight: 6, flexShrink: 0 {RB}{RB}>{LB}inlineForm.currency{RB}</span>")
l(f"                          <input type={dq}text{dq} inputMode={dq}numeric{dq}")
l(f"                            value={LB}amountDisplay{RB}")
l(f"                            onChange={LB}e => handleAmountChange(e.target.value){RB}")
l(f"                            onFocus={LB}handleAmountFocus{RB}")
l(f"                            onBlur={LB}handleAmountBlur{RB}")
l(f"                            placeholder={dq}0{dq}")
l(f"                            style={LB}{LB} ...inputStyle, textAlign: {q}right{q}, flex: 1, borderBottom: {q}none{q}, padding: {q}3px 0{q} {RB}{RB}")
l("                          />")
l("                        </div>")
l("                      </div>")
l("                      {/* VALUE DATE */}")
l("                      <div style={fieldCell}>")
l("                        <label style={{ ...labelStyle, color: errDate ? S.red : S.textTertiary }}>")
l(f"                          VALUE DATE {LB}errDate && <span style={LB}{LB} color: S.red, fontWeight: 400, letterSpacing: {q}0.04em{q} {RB}{RB}> {chr(8212)} {LB}errDate{RB}</span>{RB}")
l("                        </label>")
l("                        <InlineDatePicker")
l(f"                          value={LB}inlineForm.value_date{RB}")
l(f"                          onChange={LB}v => setInlineField({q}value_date{q}, v){RB}")
l(f"                          onBlur={LB}() => touchInline({q}value_date{q}){RB}")
l("                          hasError={!!errDate}")
l("                          focusedField={focusedField}")
l(f"                          fieldName={dq}value_date{dq}")
l(f"                          onFocus={LB}() => setFocusedField({q}value_date{q}){RB}")
l("                        />")
l("                      </div>")
l("                      {/* STATUS */}")
l("                      <div style={fieldCell}>")
l("                        <label style={labelStyle}>STATUS</label>")
l("                        <select")
l(f"                          value={LB}inlineForm.status{RB}")
l(f"                          onChange={LB}e => setInlineField({q}status{q}, e.target.value as TradeRow[{q}status{q}]){RB}")
l(f"                          onFocus={LB}() => setFocusedField({q}status{q}){RB}")
l("                          onBlur={() => setFocusedField(null)}")
l(f"                          style={LB}{LB} ...inputStyle, cursor: {q}pointer{q}, borderBottom: fb({q}status{q}, false) {RB}{RB}")
l("                        >")
l(f"                          <option value={dq}CONFIRMED{dq}>CONFIRMED</option>")
l(f"                          <option value={dq}FORECAST{dq}>FORECAST</option>")
l("                        </select>")
l("                      </div>")
l("                      {/* DESCRIPTION */}")
l("                      <div style={fieldCell}>")
l("                        <label style={labelStyle}>DESCRIPTION</label>")
l(f"                        <input type={dq}text{dq} value={LB}inlineForm.description ?? {q}{q}{RB}")
l(f"                          onChange={LB}e => setInlineField({q}description{q}, e.target.value){RB}")
l(f"                          onFocus={LB}() => setFocusedField({q}description{q}){RB}")
l("                          onBlur={() => setFocusedField(null)}")
l(f"                          placeholder={dq}Optional note{dq}")
l(f"                          style={LB}{LB} ...inputStyle, borderBottom: fb({q}description{q}, false) {RB}{RB}")
l("                        />")
l("                      </div>")
l("                    </div>")
l("                    </>")
l("                  );")
l("                })()}")
l("")
l("                {/* Submit row */}")
l(f"                <div style={LB}{LB} display: {q}flex{q}, alignItems: {q}center{q}, justifyContent: {q}space-between{q}, gap: 10, padding: {q}8px 14px{q}, borderTop: {bt}1px solid ${LB}S.borderSoft{RB}{bt} {RB}{RB}>")
l(f"                  <span style={LB}{LB} fontFamily: S.fontMono, fontSize: {q}0.6875rem{q}, color: S.textTertiary, letterSpacing: {q}0.04em{q}, overflow: {q}hidden{q}, textOverflow: {q}ellipsis{q}, whiteSpace: {q}nowrap{q} {RB}{RB}>")
l("                    {(() => {")
l(f"                      const parts: string[] = [];")
l(f"                      if (inlineForm.type) parts.push(inlineForm.type);")
l(f"                      if (inlineForm.currency) parts.push(inlineForm.currency);")
l(f"                      if (inlineForm.amount > 0) parts.push(new Intl.NumberFormat({q}en-US{q}).format(inlineForm.amount));")
l(f"                      if (inlineForm.value_date) parts.push(inlineForm.value_date.slice(0, 7));")
l(f"                      return parts.length > 1 ? parts.join({q} {U00B7} {q}) : {q}Fill fields above to preview{q};")
l("                    })()}")
l("                  </span>")
l(f"                  <div style={LB}{LB} display: {q}flex{q}, gap: 8, flexShrink: 0 {RB}{RB}>")
l(f"                    <button type={dq}button{dq}")
l(f"                      onClick={LB}() => {{ setInlineForm(EMPTY_INLINE); setInlineTouched({{}}); setAmountDisplay({q}{q}); setFocusedField(null); }}{RB}")
l(f"                      style={LB}{LB} fontFamily: S.fontMono, fontSize: {q}0.75rem{q}, letterSpacing: {q}0.04em{q}, padding: {q}7px 14px{q}, border: {bt}1px solid ${LB}S.border{RB}{bt}, color: S.textTertiary, background: {q}transparent{q}, cursor: {q}pointer{q} {RB}{RB}")
l("                    >CLEAR</button>")
l(f"                    <button type={dq}button{dq}")
l("                      onClick={handleInlineSave}")
l("                      disabled={inlineSaving}")
l(f"                      style={LB}{LB} fontFamily: S.fontMono, fontSize: {q}0.75rem{q}, letterSpacing: {q}0.04em{q}, fontWeight: 700, padding: {q}7px 18px{q}, border: {bt}1px solid ${LB}inlineValid ? S.cyan : S.border{RB}{bt}, color: inlineValid ? S.cyan : S.textTertiary, background: inlineValid ? {bt}color-mix(in srgb, ${LB}S.cyan{RB} 6%, transparent){bt} : {q}transparent{q}, cursor: inlineSaving ? {q}not-allowed{q} : {q}pointer{q}, opacity: inlineSaving ? 0.6 : 1, transition: {q}all 0.1s{q} {RB}{RB}")
l(f"                    >{LB}inlineSaving ? {q}SAVING{chr(8230)}{q} : {q}+ ADD POSITION{q}{RB}</button>")
l("                  </div>")
l("                </div>")
l("              </div>")

new_form = nl.join(L)
print(f"New form section: {len(new_form)} chars")

PAGE = "D:/Synexiun/1-SynexFund/HedgeCalc/FXDemo/frontend/src/app/input/page.tsx"
with open(PAGE, "r", encoding="utf-8") as file: content = file.read()
print(f"File: {len(content)} chars")

# Find old form section
grid_idx = content.find("{/* Form grid */}")
submit_idx = content.find("{/* Submit row */}", grid_idx)
add_pos_idx = content.find(chr(39) + "+ ADD POSITION" + chr(39), submit_idx)
close1 = content.find("</div>", add_pos_idx)
close2 = content.find("</div>", close1 + 6)
section_end = close2 + 6
old_form = content[grid_idx:section_end]
print(f"Old form: {len(old_form)} chars")

content = content[:grid_idx] + new_form + content[section_end:]
with open(PAGE, "w", encoding="utf-8") as wf: wf.write(content)
print(f"E4 form replaced. File now: {len(content)} chars")
