# backend/tests/test_golden_recommend_case01.py
from __future__ import annotations

import copy
import json
from typing import Any, Dict, Mapping, Optional
from unittest.mock import patch

import pytest

from backend.app.engine.recommend import recommend


def _stub_exposure(payload: Any, *, policy: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:
    """Stub exposure that returns the format recommend.py expects (empty exposures for empty positions)."""
    return {"exposures": [], "rejected": []}


def _stub_mapper(payload: Any, *, policy: Optional[Mapping[str, Any]] = None) -> Dict[str, Any]:
    """Stub instrument mapper that returns the format recommend.py expects."""
    return {"mapped_instruments": [], "rejected": []}


def _deep_sort(obj: Any) -> Any:
    """
    Deterministic normalization helper:
      - dicts: sorted by key
      - lists: preserved order (order is meaningful for ranked outputs)
    """
    if isinstance(obj, dict):
        return {k: _deep_sort(obj[k]) for k in sorted(obj.keys())}
    if isinstance(obj, list):
        return [_deep_sort(x) for x in obj]
    return obj


def _strip_runtime_fields(obj: Any) -> Any:
    """
    Remove runtime-variant fields so we can assert determinism on the *semantic output*.

    NOTE:
      Some engine traces include timestamps/duration fields that naturally vary between runs.
      This test intentionally ignores those fields and validates that the *content* is identical.

      output_fingerprint / input_fingerprint in trace stages are hashes computed from
      stage outputs that may include duration_ms (e.g., hedge_sizer embeds duration_ms in
      its return value).  Those hashes are therefore naturally runtime-variant and must be
      excluded from the determinism assertion.

      trace_fingerprint is derived from stages (which contain output_fingerprint), so it too
      must be stripped.

      request_id fields generated by individual engine modules may be timestamp-derived
      (e.g., exposure.py: f"exp_{int(t0 * 1_000_000)}") and must be stripped as well.
    """
    _RUNTIME_KEYS = frozenset({
        "duration_ms",
        "timestamps",
        "generated_at_ms",
        "started_at_ms",
        "ended_at_ms",
        # pre-computed fingerprints that incorporate non-deterministic stage outputs
        "output_fingerprint",
        "input_fingerprint",
        "trace_fingerprint",
        # timestamp-derived request IDs emitted by individual engine modules
        "request_id",
    })
    if isinstance(obj, dict):
        out: Dict[str, Any] = {}
        for k, v in obj.items():
            if k in _RUNTIME_KEYS:
                continue
            out[k] = _strip_runtime_fields(v)
        return out
    if isinstance(obj, list):
        return [_strip_runtime_fields(x) for x in obj]
    return obj


def _normalized_output(out: Mapping[str, Any]) -> Dict[str, Any]:
    """
    Normalize recommend() output for deterministic comparison:
      - remove runtime-variant fields (duration/timestamps)
      - deep-sort dict keys (to avoid incidental ordering noise)
    """
    return _deep_sort(_strip_runtime_fields(dict(out)))


def _case01_payload() -> Dict[str, Any]:
    """
    Case 01: Minimal end-to-end pipeline run with explicit baseline scenario.
    This is intentionally conservative:
      - no reliance on external pricing feeds
      - no need for instrument specs/meta to be present to complete orchestration
      - validates safe failures + deterministic behavior
    """
    return {
        "positions": [],  # empty positions list; exposure engine returns zero exposure deterministically
        "market": {
            "prices": {},
            "option_deltas": {},
            "sensitivities": {},
        },
        "instrument_specs": {},
        "instrument_meta": {},
        "assumptions": {
            "holding_period_days": 21,
            "spreads_bps": {},
            "fees_per_contract": {},
            "margin_rate": {},
            "funding_rate_annual": {},
            "option_premium_per_contract": {},
        },
        "scenarios": [
            {
                "scenario_id": "BASELINE",
                "shocks": {"equity_move_pct": 0.0, "vol_move_pct": 0.0, "rates_move_bps": 0.0},
            }
        ],
        # keep stage outputs enabled so we can validate cross-stage contract invariants
        "policy": {"include_stage_outputs": True},
    }


def test_recommend_case01_is_deterministic_across_runs() -> None:
    payload = _case01_payload()

    with patch("backend.app.engine.exposure.compute_exposure", side_effect=_stub_exposure), \
         patch("backend.app.engine.instrument_mapper.map_instruments", side_effect=_stub_mapper):
        out1 = recommend(copy.deepcopy(payload), policy=payload.get("policy"))
        out2 = recommend(copy.deepcopy(payload), policy=payload.get("policy"))

    n1 = _normalized_output(out1)
    n2 = _normalized_output(out2)

    # 1) Plan identity should be stable for identical inputs
    assert n1.get("plan_id") == n2.get("plan_id")

    # 2) The full semantic output (minus runtime fields) must match exactly
    assert n1 == n2


def test_recommend_case01_is_stable_under_dict_reordering() -> None:
    """
    Same payload, different insertion order, must yield same plan_id and same normalized output.
    """
    payload_a = _case01_payload()
    payload_b = json.loads(json.dumps(payload_a))  # re-materialize -> new dict insertion order

    with patch("backend.app.engine.exposure.compute_exposure", side_effect=_stub_exposure), \
         patch("backend.app.engine.instrument_mapper.map_instruments", side_effect=_stub_mapper):
        out_a = recommend(copy.deepcopy(payload_a), policy=payload_a.get("policy"))
        out_b = recommend(copy.deepcopy(payload_b), policy=payload_b.get("policy"))

    na = _normalized_output(out_a)
    nb = _normalized_output(out_b)

    assert na.get("plan_id") == nb.get("plan_id")
    assert na == nb


def test_recommend_case01_contract_invariants() -> None:
    """
    Cross-module contract invariants:
      - stages exist when include_stage_outputs=True
      - required top-level keys exist
      - rejections are present and structurally valid (even if empty)
    """
    payload = _case01_payload()
    with patch("backend.app.engine.exposure.compute_exposure", side_effect=_stub_exposure), \
         patch("backend.app.engine.instrument_mapper.map_instruments", side_effect=_stub_mapper):
        out = recommend(copy.deepcopy(payload), policy=payload.get("policy"))
    n = _normalized_output(out)

    assert isinstance(n.get("plan_id"), str) and len(n["plan_id"]) > 0
    assert isinstance(n.get("summary"), dict)
    assert isinstance(n.get("meta"), dict)
    assert "decision_trace" in n["meta"]

    # stages present because we requested them
    assert "stages" in n
    stages = n["stages"]
    assert isinstance(stages, dict)

    # Each stage should return a dict-like payload
    for key in (
        "exposure",
        "risk_classifier",
        "strategy_selector",
        "instrument_mapper",
        "hedge_sizer",
        "cost_engine",
        "scenario_engine",
    ):
        assert key in stages
        assert isinstance(stages[key], dict)

    # Plan object present because include_stage_outputs=True
    assert "plan" in n
    plan = n["plan"]
    assert isinstance(plan, dict)

    # Rejections must exist and be dict of lists (even if empty)
    # v1.0.3: all 7 stages contribute rejections to plan_core (affects plan_id hash domain)
    assert "rejections" in plan and isinstance(plan["rejections"], dict)
    for bucket in (
        "exposure",
        "risk_classifier",
        "strategy_selector",
        "instrument_mapper",
        "hedge_sizer",
        "cost_engine",
        "scenario_engine",
    ):
        assert bucket in plan["rejections"], f"Missing rejection bucket: {bucket}"
        assert isinstance(plan["rejections"][bucket], list)
