#!/usr/bin/env python3
"""NEXUS Hook: SessionStart — heal, migrate, load context, show dashboard + recommendations."""
import io
import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

# Fix Windows encoding for Unicode box-drawing characters
if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# Add parent paths for imports
_hook_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(_hook_dir.parent.parent))  # .claude/

try:
    from nexus.db.connection import get_connection, transaction, readonly_connection
    from nexus.db.schema import initialize_database
    from nexus.db.integrity import full_integrity_check
    from nexus.db.migrations import needs_migration, run_migrations
    from nexus.security.hash_chain import append_to_chain, get_chain_length
    from nexus.dashboard.renderer import render_full_dashboard
    from nexus.constants import DB_PATH, STATE_DIR, STATE_FILES

    # ── Step 1: Ensure DB exists ──────────────────────────────────────
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not DB_PATH.exists():
        with transaction() as conn:
            initialize_database(conn)

    # ── Step 2: Run healing checks ────────────────────────────────────
    issues = []
    with transaction() as conn:
        results = full_integrity_check(conn)
        for name, passed, msg in results:
            if not passed:
                issues.append((name, msg))
            # Update check record
            conn.execute(
                "UPDATE integrity_checks SET last_run = datetime('now'), last_result = ? "
                "WHERE name = ?",
                ("pass" if passed else "fail", name),
            )

    # Auto-repair state files
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    for sf in STATE_FILES:
        if not sf.exists():
            sf.write_text(f"# {sf.stem}\n\n> Auto-generated by NEXUS\n", encoding="utf-8")

    if issues:
        for name, msg in issues:
            print(f"  [HEAL] {name}: {msg}", file=sys.stderr)

    # ── Step 3: Run migrations if needed ──────────────────────────────
    with transaction() as conn:
        if needs_migration(conn):
            applied = run_migrations(conn)
            for desc in applied:
                print(f"  [MIGRATE] {desc}")

    # ── Step 4: Load context ──────────────────────────────────────────
    with readonly_connection() as conn:
        active_patterns = conn.execute(
            "SELECT COUNT(*) as cnt FROM patterns WHERE status IN ('promoted','canon')"
        ).fetchone()["cnt"]

        open_risks = conn.execute(
            "SELECT COUNT(*) as cnt FROM risks WHERE status = 'open'"
        ).fetchone()["cnt"]

        open_work = conn.execute(
            "SELECT COUNT(*) as cnt FROM work_items WHERE status NOT IN ('done','cancelled')"
        ).fetchone()["cnt"]

        chain_len = get_chain_length(conn)

        # ── Step 5: Show dashboard ────────────────────────────────────
        print(render_full_dashboard(conn))

        # ── Step 6: Show top 3 recommendations ───────────────────────
        recs = conn.execute(
            "SELECT r.recommendation, r.score, r.priority "
            "FROM recommendations r "
            "WHERE (r.expires_at IS NULL OR r.expires_at > datetime('now')) "
            "ORDER BY r.score DESC LIMIT 3"
        ).fetchall()

    if recs:
        print("\n  Top Recommendations:")
        for rec in recs:
            score_bar = "█" * int(rec["score"] * 10) + "░" * (10 - int(rec["score"] * 10))
            print(f"    [{rec['priority'].upper()}] {rec['recommendation']}")
            print(f"      Score: {score_bar} {rec['score']:.2f}")
    else:
        print("\n  No recommendations yet (system is learning)")

    # Summary line
    print(f"\n  Context: {active_patterns} active patterns | {open_risks} open risks | {open_work} work items | chain: {chain_len}")

except Exception as e:
    # Never crash — report and continue
    print(f"[NEXUS SessionStart] Error: {e}", file=sys.stderr)
