import type { PolicyConfig } from '../api/types';

export interface PolicyPreset {
  id: string;
  name: string;
  shortName: string;
  description: string;
  targetAudience: string;
  riskPosture: 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';
  category: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  formula: string;           // display formula for tooltip
  formulaExplain: string;    // plain-English explanation of the formula
  rationale: string;         // why this preset exists / real-world use
  policy: PolicyConfig;
}

export const POLICY_PRESETS: PolicyPreset[] = [
  // ─── SME / STARTUP ──────────────────────────────────────────────────────────
  {
    id: 'small-business',
    name: 'Small Business / Startup',
    shortName: 'SME',
    description: 'No minimum trade size — every bucket executes regardless of notional. Built for SMEs, startups, and early-stage hedgers with smaller transaction volumes.',
    targetAudience: 'SMEs, startups, freelancers, small importers/exporters with sub-$500K exposures',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.5 × FF,  min = $0',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows + 50% of Forecast Flows. No minimum trade size filter — every bucket executes even at very small notionals. Avoids the suppression issue small businesses face with standard corporate presets.',
    rationale: 'Standard corporate presets set minimum trade sizes ($25k–$500k) to avoid bank execution costs on tiny tickets. For SMEs hedging their first transactions, this suppresses all buckets. Setting min = $0 lets every exposure get a hedge ticket, regardless of size.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.50 },
      cost_assumptions: { spread_bps: 25 },
      execution_product: 'NDF',
      min_trade_size_usd: 0,
    },
  },

  // ─── CORPORATE ──────────────────────────────────────────────────────────────
  {
    id: 'full-protection',
    name: 'Full Protection',
    shortName: 'FULL',
    description: 'Maximum hedge coverage for all confirmed and forecast flows. Zero FX tolerance.',
    targetAudience: 'Import-dependent manufacturers, regulated utilities, fixed-price contracts',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 1.0 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 100% of Forecast Flows. Eliminates all open FX risk on the balance sheet.',
    rationale: 'Used by companies with fixed-price customer contracts in USD where any FX move directly erodes margin. Common in aerospace supply chains and infrastructure projects.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 1.0 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
  },
  {
    id: 'conservative-treasury',
    name: 'Conservative Treasury',
    shortName: 'CNSV',
    description: 'Full confirmed coverage, minimal forecast hedging. Board-mandated treasury policy.',
    targetAudience: 'Investment-grade corporates, regulated entities, public companies',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.25 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 25% of Forecast Flows. Protects firm commitments fully; accepts limited forecast variance.',
    rationale: 'Standard for CFO-mandated policies at listed companies. Board approves 25% forecast ratio to avoid over-hedging speculative pipelines while locking confirmed A/P.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.25 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 100000,
    },
  },
  {
    id: 'balanced-corporate',
    name: 'Balanced Corporate',
    shortName: 'BLNC',
    description: 'Full confirmed coverage, moderate forecast hedging. Standard mid-market FX program.',
    targetAudience: 'Mid-market corporates, manufacturing, distribution',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.5 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 50% of Forecast Flows. Balances cost certainty with forecast participation.',
    rationale: 'The most common treasury policy globally. Hedges all firm orders while covering half the pipeline, reflecting typical 50–60% forecast accuracy in mid-market.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.5 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 50000,
    },
  },
  {
    id: 'active-risk-mgmt',
    name: 'Active Risk Management',
    shortName: 'ACTV',
    description: 'High coverage across confirmed and forecast flows. Active FX risk mandate with tactical overlay.',
    targetAudience: 'Large corporates, frequent hedgers, treasury centres',
    riskPosture: 'AGGRESSIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.75 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 75% of Forecast Flows. High forecast ratio reflects strong pipeline visibility and active risk mandate.',
    rationale: 'Used by corporates with high forecast accuracy (>80%) and treasury teams empowered to run active FX books. Typical in automotive and consumer goods multinationals.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.75 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
  },
  {
    id: 'cost-sensitive',
    name: 'Cost-Sensitive Hedger',
    shortName: 'COST',
    description: 'Confirmed-only coverage. Hedges firm commitments only — avoids forecast hedging cost.',
    targetAudience: 'SMEs, cost-constrained treasuries, seasonal businesses',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.0 × FF',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows only. No forecast hedging. Slight under-hedge on confirmed to accommodate minor amendments without unwind cost.',
    rationale: 'Common in SMEs where treasury resources are limited. 80% confirmed ratio accounts for typical 5–20% contract amendment rate, avoiding costly unwind of over-hedged positions.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.8, forecast: 0.0 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 75000,
    },
  },
  {
    id: 'layered-rolling',
    name: 'Layered Rolling',
    shortName: 'LAYR',
    description: 'Graduated hedge build-up over 12 months. Avoids locking full exposure at a single spot rate.',
    targetAudience: 'Exporters, commodity traders, businesses with rolling 12-month pipelines',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H_t = CF_t + (1 - t/T) × FF_t',
    formulaExplain: 'Near-term confirmed flows hedged 100%. Forecast ratio declines with horizon: near-term at 60%, far-term at lower coverage. Achieves time-weighted average rate across the hedging window.',
    rationale: 'Prevents rate concentration risk. A company that hedges at the same time each year risks adverse timing. Layering achieves an average rate across the full hedging window.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.6 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
  },

  // ─── FINANCIAL ──────────────────────────────────────────────────────────────
  {
    id: 'bank-trading-book',
    name: 'Bank Trading Book',
    shortName: 'BANK',
    description: 'Tight spread, high minimum, NDF-only. Mirrors interbank desk execution parameters.',
    targetAudience: 'Bank subsidiaries, financial institutions, proprietary trading desks',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF + 0.9 × FF, spread ≤ 2 bps',
    formulaExplain: 'Near-full coverage with interbank spread assumptions. 90% forecast ratio reflects high-confidence flow desks. Spread at 2 bps = wholesale institutional pricing tier.',
    rationale: 'Financial institutions hedge near-100% to maintain clean accounting books. The 2 bps spread reflects actual interbank cost, not retail FX mark-up.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.9 },
      cost_assumptions: { spread_bps: 2.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 500000,
    },
  },
  {
    id: 'asset-manager',
    name: 'Asset Manager',
    shortName: 'AMGR',
    description: 'Benchmark-relative hedging. Partial confirmed hedge, minimal forecast. Tracks mandate benchmark.',
    targetAudience: 'Fund managers, pension funds, sovereign wealth funds',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = β × CF,  β ∈ [0.5, 1.0]',
    formulaExplain: 'Hedge ratio β is set by the investment mandate benchmark. Typically 50–75% of confirmed flows. Forecast flows not hedged — treated as active currency alpha opportunity.',
    rationale: 'Most fund mandates specify a currency hedge ratio (e.g., 50% benchmark hedge). Forecast flows are left open as active currency views are part of the return profile.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.75, forecast: 0.0 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 250000,
    },
  },
  {
    id: 'private-equity',
    name: 'Private Equity',
    shortName: 'PE',
    description: 'Exit-date hedging. Protects terminal valuation and IRR, not operating flows.',
    targetAudience: 'PE funds, M&A teams, cross-border acquisition financing',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF_exit,  tenor = T_exit',
    formulaExplain: 'Full hedge on exit proceeds only via single long-dated forward locked at acquisition date. Tenor matches expected hold period. Protects USD IRR from FX drift over the hold.',
    rationale: 'PE investors care about USD-denominated IRR. A 10% FX move over a 5-year hold period destroys a full year of value creation. Exit-date forward locks the conversion rate.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.1 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 1000000,
    },
  },
  {
    id: 'insurance-reserves',
    name: 'Insurance Reserves',
    shortName: 'INSR',
    description: 'Liability-matching hedge. Matches reserve currency to claims currency. Solvency II aligned.',
    targetAudience: 'Insurance companies, reinsurers, annuity providers',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × L_fx,  L_fx = FX-denominated liabilities',
    formulaExplain: 'Hedge notional = 100% of FX-denominated reserve liabilities. Confirmed-only hedging. Forecast claims provisioned via actuarial buffer, not FX forwards.',
    rationale: 'Regulators require insurers to match asset and liability currencies. A currency mismatch creates solvency ratio volatility that can trigger regulatory intervention.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.15 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
  },

  // ─── SOVEREIGN ──────────────────────────────────────────────────────────────
  {
    id: 'sovereign-debt-service',
    name: 'Sovereign Debt Service',
    shortName: 'SOVR',
    description: 'Full USD debt service hedging. Protects sovereign budget from FX-driven debt cost spikes.',
    targetAudience: 'Government treasuries, public sector entities, development banks',
    riskPosture: 'CONSERVATIVE',
    category: 'SOVEREIGN',
    formula: 'H = 1.0 × D_USD,  D_USD = annual USD debt coupon + principal',
    formulaExplain: 'Full hedge on all USD-denominated debt service (principal + coupon). No forecast hedging of revenue — those flow through the annual budget process separately.',
    rationale: 'A 15% MXN depreciation can add 1–2% of GDP to sovereign debt service costs. Governments with USD bonds hedge coupon/principal flows to protect fiscal space and credit ratings.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.0 },
      cost_assumptions: { spread_bps: 2.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
  },
  {
    id: 'export-proceeds',
    name: 'Export Proceeds',
    shortName: 'XPRT',
    description: 'Commodity export receipts hedging. Locks USD revenue against local currency depreciation.',
    targetAudience: 'State-owned commodity exporters, mining companies, oil & gas NOCs',
    riskPosture: 'MODERATE',
    category: 'SOVEREIGN',
    formula: 'H = 0.6 × Q × P_fwd',
    formulaExplain: '60% of expected export revenue hedged: volume (Q) from production forecast × forward commodity price (P_fwd). 40% left open for commodity price upside.',
    rationale: 'PEMEX, Codelco, and similar SOEs hedge 50–70% of expected receipts. Full hedging sacrifices commodity upside; zero hedging exposes the national budget to commodity AND FX shocks simultaneously.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.6 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 2000000,
    },
  },
  {
    id: 'central-bank-reserves',
    name: 'Central Bank FX Ops',
    shortName: 'CBNK',
    description: 'Reserve management overlay. Minimal hedging — intervention-ready liquidity maintained.',
    targetAudience: 'Central banks, monetary authorities, FX reserve managers',
    riskPosture: 'AGGRESSIVE',
    category: 'SOVEREIGN',
    formula: 'H = min(0.1 × R, VaR_limit)',
    formulaExplain: 'Hedge no more than 10% of reserves or the VaR daily limit, whichever is smaller. Reserves must remain deployable for market intervention — hedging constrains liquidity.',
    rationale: 'Central banks rarely hedge reserves as they need FX liquidity for market interventions. When they do hedge, it is marginal overlays only. This preset captures that operational reality.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.1, forecast: 0.0 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000000,
    },
  },

  // ─── SECTOR-SPECIFIC ────────────────────────────────────────────────────────
  {
    id: 'airline-fuel',
    name: 'Airline / Aviation',
    shortName: 'AIRL',
    description: 'Jet fuel cost + USD revenue hedge. Covers fuel payables and USD-denominated ticket revenue.',
    targetAudience: 'Airlines, charter operators, aviation lessors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H_fuel = 0.7 × Q_fuel × P_jet;  H_rev = 0.5 × USD_rev',
    formulaExplain: 'Fuel payables: hedge 70% of projected fuel volume at forward jet fuel price. USD revenue: hedge 50% of forecast USD ticket sales to protect MXN revenue floor.',
    rationale: 'IATA recommends 50–70% fuel cost hedging for airlines. Most LatAm carriers (Aeromexico, Avianca) hedge fuel and USD revenue separately to manage both cost and revenue FX legs.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
  },
  {
    id: 'tech-saas',
    name: 'Technology / SaaS',
    shortName: 'TECH',
    description: 'USD revenue, MXN cost base. Light hedge on USD receivables — preserves natural hedge benefit.',
    targetAudience: 'SaaS companies, technology exporters, nearshore services',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.5 × ARR_USD (6-month rolling)',
    formulaExplain: 'Hedge 50% of Annual Recurring Revenue via 6-month rolling forwards. Remaining 50% benefits from MXN depreciation (natural cost-base hedge). Balances floor protection with upside.',
    rationale: 'Tech companies with USD revenue and MXN cost bases have a natural hedge — MXN depreciation expands margins. Hedging half the USD revenue locks a floor without sacrificing the natural hedge benefit.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.5, forecast: 0.3 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },
  {
    id: 'real-estate-dev',
    name: 'Real Estate / REIB',
    shortName: 'REIT',
    description: 'USD construction cost hedge by project phase. Protects import material payables.',
    targetAudience: 'Real estate developers, construction groups, hotel chains',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × Import_AP (per project phase)',
    formulaExplain: 'Full hedge on confirmed USD import payables (steel, equipment, FF&E). Phased by project milestone. Forecast exposure from future phases left open pending permits and design approval.',
    rationale: 'Real estate projects have fixed USD import costs (elevators, HVAC, finishes) priced at contract award. Any FX move after contract locks in a loss. Full hedge on confirmed AP is industry standard.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.2 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 200000,
    },
  },
  {
    id: 'pharma-import',
    name: 'Pharma / Healthcare',
    shortName: 'PHRM',
    description: 'API and equipment USD import hedging. Regulatory margin protection for essential medicines.',
    targetAudience: 'Pharmaceutical importers, hospital groups, medical device distributors',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = min(1.0 × CF,  regulatory_price_cap / spot)',
    formulaExplain: 'Full hedge on confirmed API import payables, subject to regulatory price cap. If FX move would breach the COFEPRIS price threshold, the hedge notional is capped at the breakeven.',
    rationale: 'Pharma companies in MX operate under price controls. A 20% FX move on active pharmaceutical ingredients (APIs) cannot be passed to patients — it destroys operating margins entirely.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.4 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'agri-commodity',
    name: 'Agriculture / Commodity',
    shortName: 'AGRI',
    description: 'Harvest-season USD receipt hedging. Locks exchange rate at planting for harvest proceeds.',
    targetAudience: 'Agribusiness, grain traders, commodity exporters, cooperatives',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.7 × E[Harvest_USD],  σ_volume = 0.15',
    formulaExplain: '70% of expected harvest USD proceeds hedged at planting (6 months forward). Volume uncertainty buffer of 15% — actual harvest may vary. Excess or deficit rolls to next season.',
    rationale: 'Farmers lock a floor rate at planting. 100% hedging is impossible as harvest volume is uncertain. 70% = expected minimum harvest at 1σ confidence, protecting downside without over-hedging.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'auto-supply-chain',
    name: 'Automotive Supply Chain',
    shortName: 'AUTO',
    description: 'Tier-1/2 supplier policy. Full USD component cost hedge with receivable netting.',
    targetAudience: 'Auto parts manufacturers, Tier-1/2 suppliers, maquiladoras',
    riskPosture: 'AGGRESSIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × AP_USD − 0.8 × AR_USD (net exposure)',
    formulaExplain: 'Net hedge = Fully hedge USD payables (raw materials) minus 80% of USD receivables (OEM invoices). Netting payables against receivables reduces hedge cost by 60–70% vs. gross hedging.',
    rationale: 'Auto suppliers buy USD-denominated steel and sell to USD-paying OEMs. The natural hedge is high but imperfect due to JIT timing mismatches. Netting dramatically reduces FX hedge cost.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.8 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },
  {
    id: 'retail-importer',
    name: 'Retail Importer',
    shortName: 'RETL',
    description: 'Seasonal inventory hedge. Locks USD purchase cost for holiday season buying windows.',
    targetAudience: 'Retailers, e-commerce importers, consumer goods distributors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.9 × PO_USD,  tenor = payment_terms',
    formulaExplain: '90% of placed purchase orders hedged at order date. 10% buffer for cancellations and returns. Hedge tenor matches ocean freight + payment terms (typically 60–120 days).',
    rationale: 'A retailer placing holiday orders in July faces a December payment. A 10% FX move between order and payment dates destroys the margin on that inventory. Hedge at PO date locks COGS.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.4 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },

  // ─── SECTOR EXPANSION ───────────────────────────────────────────────────────
  {
    id: 'hospitality-tourism',
    name: 'Hospitality / Tourism',
    shortName: 'HSPT',
    description: 'Seasonal FX hedging for hotel groups and tour operators with USD-denominated bookings and supplier contracts.',
    targetAudience: 'Hotel chains, resort operators, tour operators, cruise lines, travel agencies',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.7 × B_USD + 0.4 × F_USD',
    formulaExplain: 'Hedge 70% of confirmed USD bookings (advance reservations) and 40% of forecast revenue. Seasonality creates lumpy cash flows — lower forecast ratio reflects unpredictable occupancy rates.',
    rationale: 'Hotels receive USD revenue from international guests but pay staff and suppliers in local currency. USD receipts spike in peak season; hedging 70% confirmed locks operating margin without over-hedging shoulder periods.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.70, forecast: 0.40 },
      cost_assumptions: { spread_bps: 7.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'shipping-logistics',
    name: 'Shipping / Logistics',
    shortName: 'SHIP',
    description: 'Freight cost and USD charter rate hedging for logistics operators and shipping companies.',
    targetAudience: 'Freight forwarders, logistics operators, shipping companies, port operators',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.85 × CF_USD + 0.65 × FF_USD',
    formulaExplain: 'Hedge 85% of confirmed freight contracts and 65% of forecast revenue. High forecast ratio reflects frequent contract visibility in logistics, where forward bookings extend 3–6 months.',
    rationale: 'Logistics companies earn USD freight revenue while incurring MXN port, fuel, and labor costs. The high forecast ratio reflects the industry\'s strong forward booking visibility — unlike consumer businesses, logistics contracts are signed months ahead.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.65 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
  },
  {
    id: 'mining-resources',
    name: 'Mining / Natural Resources',
    shortName: 'MINE',
    description: 'USD commodity revenue hedging for mining companies and natural resource exporters.',
    targetAudience: 'Mining companies, quarrying operators, natural resource producers, mineral exporters',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.8 × Q × P_fwd,  P_fwd = 6-month commodity forward',
    formulaExplain: '80% of projected production volume at 6-month forward commodity price. Buffer for volume variance (weather, equipment, grade variability). Leaves 20% open for commodity price upside.',
    rationale: 'Mining companies face dual commodity and FX risk. Hedging both simultaneously destroys upside. Standard practice is to lock FX on 75–85% of expected production while retaining commodity price exposure.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.55 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
  },
  {
    id: 'construction-infra',
    name: 'Construction / Infrastructure',
    shortName: 'BLDG',
    description: 'Project-based USD material cost hedge. Full confirmed coverage; minimal forecast during tender phase.',
    targetAudience: 'Construction groups, infrastructure developers, civil engineering firms, EPC contractors',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × CF_USD + 0.3 × FF_USD (tender pipeline)',
    formulaExplain: 'Full hedge on awarded contracts (steel, equipment, specialist subcontractors). Modest 30% forecast coverage for active tender pipeline. Post-contract award, forecast flows are reclassified to confirmed.',
    rationale: 'Construction firms bid fixed-price contracts months before material procurement. A 15% FX move between bid and order can wipe out the entire project margin. Full hedge on awarded contracts is standard practice in international construction.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.30 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
  },
  {
    id: 'media-entertainment',
    name: 'Media / Entertainment',
    shortName: 'MDIA',
    description: 'USD content licensing and production cost hedge for media companies, studios, and streaming platforms.',
    targetAudience: 'Media groups, film studios, streaming platforms, gaming companies, advertising agencies',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.6 × L_USD + 0.35 × P_USD',
    formulaExplain: 'Hedge 60% of confirmed content licensing revenues and 35% of production cost forecasts. Lower ratios reflect the high variability of content performance and IP licensing negotiations.',
    rationale: 'Media companies monetize content via USD licensing deals (Netflix, Apple, distribution agreements) while bearing MXN production costs. IP revenues are inherently lumpy — a single deal can represent 50% of annual FX flows, making forecast hedging risky.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.60, forecast: 0.35 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },

  // ─── CORPORATE EXPANSION ────────────────────────────────────────────────────
  {
    id: 'ngo-nonprofit',
    name: 'NGO / Non-Profit',
    shortName: 'NGO',
    description: 'Grant and donation FX protection. Full coverage of incoming USD grants to preserve programme budgets.',
    targetAudience: 'International NGOs, non-profit organisations, foundations, aid organisations',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 0.95 × G_USD + 0.8 × D_USD',
    formulaExplain: 'Hedge 95% of confirmed grant disbursements and 80% of forecast donor commitments. Near-full coverage — programmes are budget-fixed and cannot absorb FX losses without cutting field operations.',
    rationale: 'NGOs operate on fixed programme budgets in local currency. A USD grant losing 20% to FX before deployment means 20% fewer beneficiaries served. Near-full hedging at high forecast ratios is justified by formal donor pledge letters.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.95, forecast: 0.80 },
      cost_assumptions: { spread_bps: 10.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 0,
    },
  },
  {
    id: 'import-export-trader',
    name: 'Import / Export Trader',
    shortName: 'IMEX',
    description: 'Transactional hedge for active importers/exporters with high PO frequency and short tenors.',
    targetAudience: 'Trading companies, commodity traders, active importers, multi-product distributors',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 0.9 × PO_AP + 0.6 × Q_forecast',
    formulaExplain: 'Hedge 90% of placed purchase orders (accounts payable) and 60% of next-quarter forecast volume. Short tenors (30–90 days) on all tickets. High confirmed ratio reflects PO-based flow certainty.',
    rationale: 'Trading companies generate FX exposure with every cross-border transaction. The high confirmed ratio reflects that purchase orders represent firm commitments. 60% forecast hedging accounts for typical quarterly pipeline visibility in active trading books.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.90, forecast: 0.60 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'education-institutions',
    name: 'Education / Institutions',
    shortName: 'EDUC',
    description: 'Tuition revenue and USD equipment purchase hedge for universities and educational institutions.',
    targetAudience: 'Universities, international schools, training institutions, EdTech companies',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF_fees + 0.5 × FF_enrolment',
    formulaExplain: 'Full hedge on confirmed tuition fee receivables and equipment payables. 50% forecast coverage for projected enrolment-based revenue. Academic calendars create predictable semi-annual flow patterns.',
    rationale: 'Educational institutions collect USD fees from international students while paying local salaries and facilities costs. Annual enrolment cycles create predictable but lumpy FX flows, making hedging straightforward once enrolment is confirmed.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.50 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000,
    },
  },

  // ─── FINANCIAL EXPANSION ────────────────────────────────────────────────────
  {
    id: 'family-office',
    name: 'Family Office',
    shortName: 'FAML',
    description: 'Wealth preservation hedge for family offices with cross-border portfolio and real asset exposure.',
    targetAudience: 'Single-family offices, multi-family offices, UHNW wealth managers',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = 0.85 × CF_USD + 0.2 × AUM_FX',
    formulaExplain: 'Hedge 85% of confirmed cross-border flows (dividends, distributions, property proceeds) and 20% of FX-denominated AUM. Conservative forecast ratio reflects family office preference for tactical opportunism.',
    rationale: 'Family offices balance capital preservation with opportunistic FX positioning. High confirmed ratio protects property and dividend flows; low forecast ratio reflects the flexibility typical in discretionary mandates without institutional reporting constraints.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.20 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 250000,
    },
  },
  {
    id: 'hedge-fund',
    name: 'Hedge Fund',
    shortName: 'HFND',
    description: 'Alpha-focused FX programme. Near-full coverage with tight spreads for systematic trading desks.',
    targetAudience: 'Macro hedge funds, systematic FX desks, quantitative asset managers, CTA funds',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF_USD + 0.95 × FF_USD,  spread ≤ 1.5 bps',
    formulaExplain: 'Near-complete FX hedging with minimal open exposure. 95% forecast coverage reflects systematic funds\' high pipeline visibility. 1.5 bps spread reflects institutional prime brokerage rates.',
    rationale: 'Hedge funds run net-zero FX books as a rule — unintended currency exposure is a risk, not an alpha source. Near-100% hedging is standard. The 1.5 bps spread reflects prime brokerage access, not retail FX mark-ups.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.95 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 1000000,
    },
  },
  {
    id: 'vc-growth-equity',
    name: 'VC / Growth Equity',
    shortName: 'VCGR',
    description: 'Portfolio company FX protection. Selective hedging of USD capital calls and exit proceeds.',
    targetAudience: 'Venture capital funds, growth equity managers, startup investors, accelerators',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = 0.7 × CF_capital + 0.1 × FF_pipeline',
    formulaExplain: 'Hedge 70% of confirmed capital calls and distributions. Minimal forecast hedging (10%) — future portfolio valuations are highly uncertain, making forecast hedging speculative.',
    rationale: 'VC funds call and distribute capital in USD while managing portfolio companies in local currency. Capital call timing is defined at closing (high certainty); future portfolio exits are highly uncertain (minimal forecast hedge).',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.70, forecast: 0.10 },
      cost_assumptions: { spread_bps: 7.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
  },

  // ─── SECTOR EXPANSION (ENERGY & UTILITIES) ──────────────────────────────────
  {
    id: 'energy-utilities',
    name: 'Energy / Utilities',
    shortName: 'ENGY',
    description: 'USD fuel and equipment import hedging for energy companies and regulated utilities.',
    targetAudience: 'Power generators, utilities, gas distributors, renewable energy developers',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 0.95 × CF_USD + 0.7 × FF_USD',
    formulaExplain: 'Near-full hedge on confirmed fuel and equipment payables, 70% coverage on 12-month generation forecast. High forecast ratio reflects long-term offtake agreement visibility in the regulated utility sector.',
    rationale: 'Energy companies operate under regulated tariff structures — they cannot pass USD fuel cost spikes to customers mid-contract. Full confirmed hedging and high forecast coverage is regulatory standard in power generation.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.95, forecast: 0.70 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
  },
];

// Category metadata for UI grouping
export const PRESET_CATEGORIES: {
  id: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  label: string;
  description: string;
}[] = [
  { id: 'CORPORATE', label: 'Corporate',      description: 'General corporate treasury policies' },
  { id: 'FINANCIAL', label: 'Financial',       description: 'Banks, funds, and financial institutions' },
  { id: 'SOVEREIGN', label: 'Sovereign / SOE', description: 'Government and state-owned enterprises' },
  { id: 'SECTOR',    label: 'Sector-Specific', description: 'Industry-tailored hedge strategies' },
];
