import type { PolicyConfig } from '../api/types';

export interface PolicyPreset {
  id: string;
  name: string;
  shortName: string;
  description: string;
  targetAudience: string;
  riskPosture: 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';
  category: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  formula: string;           // display formula for tooltip
  formulaExplain: string;    // plain-English explanation of the formula
  rationale: string;         // why this preset exists / real-world use
  policy: PolicyConfig;
  maturity_profile: 'SHORT' | 'MEDIUM' | 'LONG' | 'MIXED';
  governance_tier: 'STANDARD' | 'ENHANCED' | 'COMMITTEE';
  evidence_grade: 'BASIC' | 'DOCUMENTED' | 'AUDITED';
  accounting_mode: 'FAIR_VALUE' | 'CASH_FLOW_HEDGE' | 'NET_INVESTMENT' | 'NONE';
}

export const POLICY_PRESETS: PolicyPreset[] = [
  // ─── SME / STARTUP ──────────────────────────────────────────────────────────
  {
    id: 'small-business',
    name: 'Small Business / Startup',
    shortName: 'SME',
    description: 'No minimum trade size — every bucket executes regardless of notional. Built for SMEs, startups, and early-stage hedgers with smaller transaction volumes.',
    targetAudience: 'SMEs, startups, freelancers, small importers/exporters with sub-$500K exposures',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.5 × FF,  min = $0',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows + 50% of Forecast Flows. No minimum trade size filter — every bucket executes even at very small notionals. Avoids the suppression issue small businesses face with standard corporate presets.',
    rationale: 'Standard corporate presets set minimum trade sizes ($25k–$500k) to avoid bank execution costs on tiny tickets. For SMEs hedging their first transactions, this suppresses all buckets. Setting min = $0 lets every exposure get a hedge ticket, regardless of size.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.50 },
      cost_assumptions: { spread_bps: 25 },
      execution_product: 'NDF',
      min_trade_size_usd: 0,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'NONE',
  },

  // ─── CORPORATE ──────────────────────────────────────────────────────────────
  {
    id: 'full-protection',
    name: 'Full Protection',
    shortName: 'FULL',
    description: 'Maximum hedge coverage for all confirmed and forecast flows. Zero FX tolerance.',
    targetAudience: 'Import-dependent manufacturers, regulated utilities, fixed-price contracts',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 1.0 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 100% of Forecast Flows. Eliminates all open FX risk on the balance sheet.',
    rationale: 'Used by companies with fixed-price customer contracts in USD where any FX move directly erodes margin. Common in aerospace supply chains and infrastructure projects.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 1.0 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'conservative-treasury',
    name: 'Conservative Treasury',
    shortName: 'CNSV',
    description: 'Full confirmed coverage, minimal forecast hedging. Board-mandated treasury policy.',
    targetAudience: 'Investment-grade corporates, regulated entities, public companies',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.25 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 25% of Forecast Flows. Protects firm commitments fully; accepts limited forecast variance.',
    rationale: 'Standard for CFO-mandated policies at listed companies. Board approves 25% forecast ratio to avoid over-hedging speculative pipelines while locking confirmed A/P.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.25 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'balanced-corporate',
    name: 'Balanced Corporate',
    shortName: 'BLNC',
    description: 'Full confirmed coverage, moderate forecast hedging. Standard mid-market FX program.',
    targetAudience: 'Mid-market corporates, manufacturing, distribution',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.5 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 50% of Forecast Flows. Balances cost certainty with forecast participation.',
    rationale: 'The most common treasury policy globally. Hedges all firm orders while covering half the pipeline, reflecting typical 50–60% forecast accuracy in mid-market.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.5 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'active-risk-mgmt',
    name: 'Active Risk Management',
    shortName: 'ACTV',
    description: 'High coverage across confirmed and forecast flows. Active FX risk mandate with tactical overlay.',
    targetAudience: 'Large corporates, frequent hedgers, treasury centres',
    riskPosture: 'AGGRESSIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.75 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 75% of Forecast Flows. High forecast ratio reflects strong pipeline visibility and active risk mandate.',
    rationale: 'Used by corporates with high forecast accuracy (>80%) and treasury teams empowered to run active FX books. Typical in automotive and consumer goods multinationals.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.75 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'FAIR_VALUE',
  },
  {
    id: 'cost-sensitive',
    name: 'Cost-Sensitive Hedger',
    shortName: 'COST',
    description: 'Confirmed-only coverage. Hedges firm commitments only — avoids forecast hedging cost.',
    targetAudience: 'SMEs, cost-constrained treasuries, seasonal businesses',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.0 × FF',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows only. No forecast hedging. Slight under-hedge on confirmed to accommodate minor amendments without unwind cost.',
    rationale: 'Common in SMEs where treasury resources are limited. 80% confirmed ratio accounts for typical 5–20% contract amendment rate, avoiding costly unwind of over-hedged positions.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.8, forecast: 0.0 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 75000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'NONE',
  },
  {
    id: 'layered-rolling',
    name: 'Layered Rolling',
    shortName: 'LAYR',
    description: 'Graduated hedge build-up over 12 months. Avoids locking full exposure at a single spot rate.',
    targetAudience: 'Exporters, commodity traders, businesses with rolling 12-month pipelines',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H_t = CF_t + (1 - t/T) × FF_t',
    formulaExplain: 'Near-term confirmed flows hedged 100%. Forecast ratio declines with horizon: near-term at 60%, far-term at lower coverage. Achieves time-weighted average rate across the hedging window.',
    rationale: 'Prevents rate concentration risk. A company that hedges at the same time each year risks adverse timing. Layering achieves an average rate across the full hedging window.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.6 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── FINANCIAL ──────────────────────────────────────────────────────────────
  {
    id: 'bank-trading-book',
    name: 'Bank Trading Book',
    shortName: 'BANK',
    description: 'Tight spread, high minimum, NDF-only. Mirrors interbank desk execution parameters.',
    targetAudience: 'Bank subsidiaries, financial institutions, proprietary trading desks',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF + 0.9 × FF, spread ≤ 2 bps',
    formulaExplain: 'Near-full coverage with interbank spread assumptions. 90% forecast ratio reflects high-confidence flow desks. Spread at 2 bps = wholesale institutional pricing tier.',
    rationale: 'Financial institutions hedge near-100% to maintain clean accounting books. The 2 bps spread reflects actual interbank cost, not retail FX mark-up.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.9 },
      cost_assumptions: { spread_bps: 2.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'FAIR_VALUE',
  },
  {
    id: 'asset-manager',
    name: 'Asset Manager',
    shortName: 'AMGR',
    description: 'Benchmark-relative hedging. Partial confirmed hedge, minimal forecast. Tracks mandate benchmark.',
    targetAudience: 'Fund managers, pension funds, sovereign wealth funds',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = β × CF,  β ∈ [0.5, 1.0]',
    formulaExplain: 'Hedge ratio β is set by the investment mandate benchmark. Typically 50–75% of confirmed flows. Forecast flows not hedged — treated as active currency alpha opportunity.',
    rationale: 'Most fund mandates specify a currency hedge ratio (e.g., 50% benchmark hedge). Forecast flows are left open as active currency views are part of the return profile.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.75, forecast: 0.0 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 250000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'AUDITED',
    accounting_mode: 'FAIR_VALUE',
  },
  {
    id: 'private-equity',
    name: 'Private Equity',
    shortName: 'PE',
    description: 'Exit-date hedging. Protects terminal valuation and IRR, not operating flows.',
    targetAudience: 'PE funds, M&A teams, cross-border acquisition financing',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF_exit,  tenor = T_exit',
    formulaExplain: 'Full hedge on exit proceeds only via single long-dated forward locked at acquisition date. Tenor matches expected hold period. Protects USD IRR from FX drift over the hold.',
    rationale: 'PE investors care about USD-denominated IRR. A 10% FX move over a 5-year hold period destroys a full year of value creation. Exit-date forward locks the conversion rate.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.1 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 1000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'NONE',
  },
  {
    id: 'insurance-reserves',
    name: 'Insurance Reserves',
    shortName: 'INSR',
    description: 'Liability-matching hedge. Matches reserve currency to claims currency. Solvency II aligned.',
    targetAudience: 'Insurance companies, reinsurers, annuity providers',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × L_fx,  L_fx = FX-denominated liabilities',
    formulaExplain: 'Hedge notional = 100% of FX-denominated reserve liabilities. Confirmed-only hedging. Forecast claims provisioned via actuarial buffer, not FX forwards.',
    rationale: 'Regulators require insurers to match asset and liability currencies. A currency mismatch creates solvency ratio volatility that can trigger regulatory intervention.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.15 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── SOVEREIGN ──────────────────────────────────────────────────────────────
  {
    id: 'sovereign-debt-service',
    name: 'Sovereign Debt Service',
    shortName: 'SOVR',
    description: 'Full USD debt service hedging. Protects sovereign budget from FX-driven debt cost spikes.',
    targetAudience: 'Government treasuries, public sector entities, development banks',
    riskPosture: 'CONSERVATIVE',
    category: 'SOVEREIGN',
    formula: 'H = 1.0 × D_USD,  D_USD = annual USD debt coupon + principal',
    formulaExplain: 'Full hedge on all USD-denominated debt service (principal + coupon). No forecast hedging of revenue — those flow through the annual budget process separately.',
    rationale: 'A 15% MXN depreciation can add 1–2% of GDP to sovereign debt service costs. Governments with USD bonds hedge coupon/principal flows to protect fiscal space and credit ratings.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.0 },
      cost_assumptions: { spread_bps: 2.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'NONE',
  },
  {
    id: 'export-proceeds',
    name: 'Export Proceeds',
    shortName: 'XPRT',
    description: 'Commodity export receipts hedging. Locks USD revenue against local currency depreciation.',
    targetAudience: 'State-owned commodity exporters, mining companies, oil & gas NOCs',
    riskPosture: 'MODERATE',
    category: 'SOVEREIGN',
    formula: 'H = 0.6 × Q × P_fwd',
    formulaExplain: '60% of expected export revenue hedged: volume (Q) from production forecast × forward commodity price (P_fwd). 40% left open for commodity price upside.',
    rationale: 'PEMEX, Codelco, and similar SOEs hedge 50–70% of expected receipts. Full hedging sacrifices commodity upside; zero hedging exposes the national budget to commodity AND FX shocks simultaneously.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.6 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 2000000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'central-bank-reserves',
    name: 'Central Bank FX Ops',
    shortName: 'CBNK',
    description: 'Reserve management overlay. Minimal hedging — intervention-ready liquidity maintained.',
    targetAudience: 'Central banks, monetary authorities, FX reserve managers',
    riskPosture: 'AGGRESSIVE',
    category: 'SOVEREIGN',
    formula: 'H = min(0.1 × R, VaR_limit)',
    formulaExplain: 'Hedge no more than 10% of reserves or the VaR daily limit, whichever is smaller. Reserves must remain deployable for market intervention — hedging constrains liquidity.',
    rationale: 'Central banks rarely hedge reserves as they need FX liquidity for market interventions. When they do hedge, it is marginal overlays only. This preset captures that operational reality.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.1, forecast: 0.0 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'NONE',
  },

  // ─── SECTOR-SPECIFIC ────────────────────────────────────────────────────────
  {
    id: 'airline-fuel',
    name: 'Airline / Aviation',
    shortName: 'AIRL',
    description: 'Jet fuel cost + USD revenue hedge. Covers fuel payables and USD-denominated ticket revenue.',
    targetAudience: 'Airlines, charter operators, aviation lessors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H_fuel = 0.7 × Q_fuel × P_jet;  H_rev = 0.5 × USD_rev',
    formulaExplain: 'Fuel payables: hedge 70% of projected fuel volume at forward jet fuel price. USD revenue: hedge 50% of forecast USD ticket sales to protect MXN revenue floor.',
    rationale: 'IATA recommends 50–70% fuel cost hedging for airlines. Most LatAm carriers (Aeromexico, Avianca) hedge fuel and USD revenue separately to manage both cost and revenue FX legs.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'tech-saas',
    name: 'Technology / SaaS',
    shortName: 'TECH',
    description: 'USD revenue, MXN cost base. Light hedge on USD receivables — preserves natural hedge benefit.',
    targetAudience: 'SaaS companies, technology exporters, nearshore services',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.5 × ARR_USD (6-month rolling)',
    formulaExplain: 'Hedge 50% of Annual Recurring Revenue via 6-month rolling forwards. Remaining 50% benefits from MXN depreciation (natural cost-base hedge). Balances floor protection with upside.',
    rationale: 'Tech companies with USD revenue and MXN cost bases have a natural hedge — MXN depreciation expands margins. Hedging half the USD revenue locks a floor without sacrificing the natural hedge benefit.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.5, forecast: 0.3 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'NONE',
  },
  {
    id: 'real-estate-dev',
    name: 'Real Estate / REIB',
    shortName: 'REIT',
    description: 'USD construction cost hedge by project phase. Protects import material payables.',
    targetAudience: 'Real estate developers, construction groups, hotel chains',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × Import_AP (per project phase)',
    formulaExplain: 'Full hedge on confirmed USD import payables (steel, equipment, FF&E). Phased by project milestone. Forecast exposure from future phases left open pending permits and design approval.',
    rationale: 'Real estate projects have fixed USD import costs (elevators, HVAC, finishes) priced at contract award. Any FX move after contract locks in a loss. Full hedge on confirmed AP is industry standard.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.2 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 200000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'pharma-import',
    name: 'Pharma / Healthcare',
    shortName: 'PHRM',
    description: 'API and equipment USD import hedging. Regulatory margin protection for essential medicines.',
    targetAudience: 'Pharmaceutical importers, hospital groups, medical device distributors',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = min(1.0 × CF,  regulatory_price_cap / spot)',
    formulaExplain: 'Full hedge on confirmed API import payables, subject to regulatory price cap. If FX move would breach the COFEPRIS price threshold, the hedge notional is capped at the breakeven.',
    rationale: 'Pharma companies in MX operate under price controls. A 20% FX move on active pharmaceutical ingredients (APIs) cannot be passed to patients — it destroys operating margins entirely.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.4 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'agri-commodity',
    name: 'Agriculture / Commodity',
    shortName: 'AGRI',
    description: 'Harvest-season USD receipt hedging. Locks exchange rate at planting for harvest proceeds.',
    targetAudience: 'Agribusiness, grain traders, commodity exporters, cooperatives',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.7 × E[Harvest_USD],  σ_volume = 0.15',
    formulaExplain: '70% of expected harvest USD proceeds hedged at planting (6 months forward). Volume uncertainty buffer of 15% — actual harvest may vary. Excess or deficit rolls to next season.',
    rationale: 'Farmers lock a floor rate at planting. 100% hedging is impossible as harvest volume is uncertain. 70% = expected minimum harvest at 1σ confidence, protecting downside without over-hedging.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'auto-supply-chain',
    name: 'Automotive Supply Chain',
    shortName: 'AUTO',
    description: 'Tier-1/2 supplier policy. Full USD component cost hedge with receivable netting.',
    targetAudience: 'Auto parts manufacturers, Tier-1/2 suppliers, maquiladoras',
    riskPosture: 'AGGRESSIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × AP_USD − 0.8 × AR_USD (net exposure)',
    formulaExplain: 'Net hedge = Fully hedge USD payables (raw materials) minus 80% of USD receivables (OEM invoices). Netting payables against receivables reduces hedge cost by 60–70% vs. gross hedging.',
    rationale: 'Auto suppliers buy USD-denominated steel and sell to USD-paying OEMs. The natural hedge is high but imperfect due to JIT timing mismatches. Netting dramatically reduces FX hedge cost.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.8 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'retail-importer',
    name: 'Retail Importer',
    shortName: 'RETL',
    description: 'Seasonal inventory hedge. Locks USD purchase cost for holiday season buying windows.',
    targetAudience: 'Retailers, e-commerce importers, consumer goods distributors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.9 × PO_USD,  tenor = payment_terms',
    formulaExplain: '90% of placed purchase orders hedged at order date. 10% buffer for cancellations and returns. Hedge tenor matches ocean freight + payment terms (typically 60–120 days).',
    rationale: 'A retailer placing holiday orders in July faces a December payment. A 10% FX move between order and payment dates destroys the margin on that inventory. Hedge at PO date locks COGS.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.4 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── SECTOR EXPANSION ───────────────────────────────────────────────────────
  {
    id: 'hospitality-tourism',
    name: 'Hospitality / Tourism',
    shortName: 'HSPT',
    description: 'Seasonal FX hedging for hotel groups and tour operators with USD-denominated bookings and supplier contracts.',
    targetAudience: 'Hotel chains, resort operators, tour operators, cruise lines, travel agencies',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.7 × B_USD + 0.4 × F_USD',
    formulaExplain: 'Hedge 70% of confirmed USD bookings (advance reservations) and 40% of forecast revenue. Seasonality creates lumpy cash flows — lower forecast ratio reflects unpredictable occupancy rates.',
    rationale: 'Hotels receive USD revenue from international guests but pay staff and suppliers in local currency. USD receipts spike in peak season; hedging 70% confirmed locks operating margin without over-hedging shoulder periods.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.70, forecast: 0.40 },
      cost_assumptions: { spread_bps: 7.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'shipping-logistics',
    name: 'Shipping / Logistics',
    shortName: 'SHIP',
    description: 'Freight cost and USD charter rate hedging for logistics operators and shipping companies.',
    targetAudience: 'Freight forwarders, logistics operators, shipping companies, port operators',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.85 × CF_USD + 0.65 × FF_USD',
    formulaExplain: 'Hedge 85% of confirmed freight contracts and 65% of forecast revenue. High forecast ratio reflects frequent contract visibility in logistics, where forward bookings extend 3–6 months.',
    rationale: 'Logistics companies earn USD freight revenue while incurring MXN port, fuel, and labor costs. The high forecast ratio reflects the industry\'s strong forward booking visibility — unlike consumer businesses, logistics contracts are signed months ahead.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.65 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'mining-resources',
    name: 'Mining / Natural Resources',
    shortName: 'MINE',
    description: 'USD commodity revenue hedging for mining companies and natural resource exporters.',
    targetAudience: 'Mining companies, quarrying operators, natural resource producers, mineral exporters',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.8 × Q × P_fwd,  P_fwd = 6-month commodity forward',
    formulaExplain: '80% of projected production volume at 6-month forward commodity price. Buffer for volume variance (weather, equipment, grade variability). Leaves 20% open for commodity price upside.',
    rationale: 'Mining companies face dual commodity and FX risk. Hedging both simultaneously destroys upside. Standard practice is to lock FX on 75–85% of expected production while retaining commodity price exposure.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.55 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'construction-infra',
    name: 'Construction / Infrastructure',
    shortName: 'BLDG',
    description: 'Project-based USD material cost hedge. Full confirmed coverage; minimal forecast during tender phase.',
    targetAudience: 'Construction groups, infrastructure developers, civil engineering firms, EPC contractors',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × CF_USD + 0.3 × FF_USD (tender pipeline)',
    formulaExplain: 'Full hedge on awarded contracts (steel, equipment, specialist subcontractors). Modest 30% forecast coverage for active tender pipeline. Post-contract award, forecast flows are reclassified to confirmed.',
    rationale: 'Construction firms bid fixed-price contracts months before material procurement. A 15% FX move between bid and order can wipe out the entire project margin. Full hedge on awarded contracts is standard practice in international construction.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.30 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'media-entertainment',
    name: 'Media / Entertainment',
    shortName: 'MDIA',
    description: 'USD content licensing and production cost hedge for media companies, studios, and streaming platforms.',
    targetAudience: 'Media groups, film studios, streaming platforms, gaming companies, advertising agencies',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.6 × L_USD + 0.35 × P_USD',
    formulaExplain: 'Hedge 60% of confirmed content licensing revenues and 35% of production cost forecasts. Lower ratios reflect the high variability of content performance and IP licensing negotiations.',
    rationale: 'Media companies monetize content via USD licensing deals (Netflix, Apple, distribution agreements) while bearing MXN production costs. IP revenues are inherently lumpy — a single deal can represent 50% of annual FX flows, making forecast hedging risky.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.60, forecast: 0.35 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'NONE',
  },

  // ─── CORPORATE EXPANSION ────────────────────────────────────────────────────
  {
    id: 'ngo-nonprofit',
    name: 'NGO / Non-Profit',
    shortName: 'NGO',
    description: 'Grant and donation FX protection. Full coverage of incoming USD grants to preserve programme budgets.',
    targetAudience: 'International NGOs, non-profit organisations, foundations, aid organisations',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 0.95 × G_USD + 0.8 × D_USD',
    formulaExplain: 'Hedge 95% of confirmed grant disbursements and 80% of forecast donor commitments. Near-full coverage — programmes are budget-fixed and cannot absorb FX losses without cutting field operations.',
    rationale: 'NGOs operate on fixed programme budgets in local currency. A USD grant losing 20% to FX before deployment means 20% fewer beneficiaries served. Near-full hedging at high forecast ratios is justified by formal donor pledge letters.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.95, forecast: 0.80 },
      cost_assumptions: { spread_bps: 10.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 0,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'import-export-trader',
    name: 'Import / Export Trader',
    shortName: 'IMEX',
    description: 'Transactional hedge for active importers/exporters with high PO frequency and short tenors.',
    targetAudience: 'Trading companies, commodity traders, active importers, multi-product distributors',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 0.9 × PO_AP + 0.6 × Q_forecast',
    formulaExplain: 'Hedge 90% of placed purchase orders (accounts payable) and 60% of next-quarter forecast volume. Short tenors (30–90 days) on all tickets. High confirmed ratio reflects PO-based flow certainty.',
    rationale: 'Trading companies generate FX exposure with every cross-border transaction. The high confirmed ratio reflects that purchase orders represent firm commitments. 60% forecast hedging accounts for typical quarterly pipeline visibility in active trading books.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.90, forecast: 0.60 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'education-institutions',
    name: 'Education / Institutions',
    shortName: 'EDUC',
    description: 'Tuition revenue and USD equipment purchase hedge for universities and educational institutions.',
    targetAudience: 'Universities, international schools, training institutions, EdTech companies',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF_fees + 0.5 × FF_enrolment',
    formulaExplain: 'Full hedge on confirmed tuition fee receivables and equipment payables. 50% forecast coverage for projected enrolment-based revenue. Academic calendars create predictable semi-annual flow patterns.',
    rationale: 'Educational institutions collect USD fees from international students while paying local salaries and facilities costs. Annual enrolment cycles create predictable but lumpy FX flows, making hedging straightforward once enrolment is confirmed.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.50 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── FINANCIAL EXPANSION ────────────────────────────────────────────────────
  {
    id: 'family-office',
    name: 'Family Office',
    shortName: 'FAML',
    description: 'Wealth preservation hedge for family offices with cross-border portfolio and real asset exposure.',
    targetAudience: 'Single-family offices, multi-family offices, UHNW wealth managers',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = 0.85 × CF_USD + 0.2 × AUM_FX',
    formulaExplain: 'Hedge 85% of confirmed cross-border flows (dividends, distributions, property proceeds) and 20% of FX-denominated AUM. Conservative forecast ratio reflects family office preference for tactical opportunism.',
    rationale: 'Family offices balance capital preservation with opportunistic FX positioning. High confirmed ratio protects property and dividend flows; low forecast ratio reflects the flexibility typical in discretionary mandates without institutional reporting constraints.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.20 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 250000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'NONE',
  },
  {
    id: 'hedge-fund',
    name: 'Hedge Fund',
    shortName: 'HFND',
    description: 'Alpha-focused FX programme. Near-full coverage with tight spreads for systematic trading desks.',
    targetAudience: 'Macro hedge funds, systematic FX desks, quantitative asset managers, CTA funds',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF_USD + 0.95 × FF_USD,  spread ≤ 1.5 bps',
    formulaExplain: 'Near-complete FX hedging with minimal open exposure. 95% forecast coverage reflects systematic funds\' high pipeline visibility. 1.5 bps spread reflects institutional prime brokerage rates.',
    rationale: 'Hedge funds run net-zero FX books as a rule — unintended currency exposure is a risk, not an alpha source. Near-100% hedging is standard. The 1.5 bps spread reflects prime brokerage access, not retail FX mark-ups.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.95 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 1000000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'ENHANCED',
    evidence_grade: 'AUDITED',
    accounting_mode: 'FAIR_VALUE',
  },
  {
    id: 'vc-growth-equity',
    name: 'VC / Growth Equity',
    shortName: 'VCGR',
    description: 'Portfolio company FX protection. Selective hedging of USD capital calls and exit proceeds.',
    targetAudience: 'Venture capital funds, growth equity managers, startup investors, accelerators',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = 0.7 × CF_capital + 0.1 × FF_pipeline',
    formulaExplain: 'Hedge 70% of confirmed capital calls and distributions. Minimal forecast hedging (10%) — future portfolio valuations are highly uncertain, making forecast hedging speculative.',
    rationale: 'VC funds call and distribute capital in USD while managing portfolio companies in local currency. Capital call timing is defined at closing (high certainty); future portfolio exits are highly uncertain (minimal forecast hedge).',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.70, forecast: 0.10 },
      cost_assumptions: { spread_bps: 7.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'STANDARD',
    evidence_grade: 'BASIC',
    accounting_mode: 'NONE',
  },

  // ─── SECTOR EXPANSION (ENERGY & UTILITIES) ──────────────────────────────────
  {
    id: 'energy-utilities',
    name: 'Energy / Utilities',
    shortName: 'ENGY',
    description: 'USD fuel and equipment import hedging for energy companies and regulated utilities.',
    targetAudience: 'Power generators, utilities, gas distributors, renewable energy developers',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 0.95 × CF_USD + 0.7 × FF_USD',
    formulaExplain: 'Near-full hedge on confirmed fuel and equipment payables, 70% coverage on 12-month generation forecast. High forecast ratio reflects long-term offtake agreement visibility in the regulated utility sector.',
    rationale: 'Energy companies operate under regulated tariff structures — they cannot pass USD fuel cost spikes to customers mid-contract. Full confirmed hedging and high forecast coverage is regulatory standard in power generation.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.95, forecast: 0.70 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── ENERGY — EXPANDED ───────────────────────────────────────────────────────
  {
    id: 'oil-gas-upstream',
    name: 'Oil & Gas Upstream (E&P)',
    shortName: 'OILG',
    description: 'USD production revenue hedge for E&P companies. Protects netback price from FX-driven local currency appreciation eroding USD revenue conversion.',
    targetAudience: 'Exploration & production companies, onshore/offshore operators, NOC subsidiaries',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.65 × Q_prod × (P_fwd − opex_local/spot)',
    formulaExplain: 'Hedge 65% of net expected production revenue (forward price less local opex in spot terms). Buffer for production volume variance of ±15% and commodity price optionality.',
    rationale: 'E&P companies earn USD from oil sales but pay operating costs in local currency. Full hedging of production revenue eliminates the natural hedge benefit when local currency depreciates (opex falls in USD terms). 65% hedge ratio balances floor protection with retention of the natural cost hedge.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.65 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'lng-exporter',
    name: 'LNG Export Operations',
    shortName: 'LNGX',
    description: 'Long-tenor USD offtake agreement hedge for LNG exporters. Matches hedge maturities to 5–20 year supply contracts with destination market price indexation.',
    targetAudience: 'LNG export terminals, natural gas producers, energy majors with LNG portfolios',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × CF_offtake + 0.4 × FF_spot_sales',
    formulaExplain: 'Full hedge on confirmed long-term offtake revenues. 40% forecast coverage for spot market sales above contract volumes. Long tenor (3–10 years) forwards or cross-currency swaps for offtake commitments.',
    rationale: 'LNG offtake agreements are 5–20 year contracts with USD fixed prices. Local currency operating costs (labor, maintenance, taxes) create a structural FX exposure over multi-year periods. Full hedging of confirmed offtake provides budget certainty for project finance covenants. Spot sales retain market exposure.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.40 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'renewable-energy',
    name: 'Renewable Energy / PPA',
    shortName: 'RENW',
    description: 'USD PPA revenue hedge for renewable energy projects with local currency construction and O&M costs. Protects project IRR during construction and operations phases.',
    targetAudience: 'Solar, wind, and hydro power developers; independent power producers; clean energy funds',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 0.90 × PPA_USD + 0.60 × FF_merchant',
    formulaExplain: 'Hedge 90% of contracted PPA revenues denominated in USD and 60% of forecast merchant power sales. Construction phase: 100% of USD equipment imports hedged. Operations phase: PPA-linked forward layering over contract life.',
    rationale: 'Renewable energy projects are financed with project loans where USD revenue covers USD-denominated debt service. Any FX depreciation of the PPA currency erodes DSCR (debt service coverage ratio) and can trigger project finance default. Near-full PPA hedging is required by most project finance lenders.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.90, forecast: 0.60 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 1000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'oil-field-services',
    name: 'Oil Field Services (OFS)',
    shortName: 'OFSC',
    description: 'USD day-rate revenue and local cost hedge for oilfield services companies with multi-jurisdiction operations.',
    targetAudience: 'Drilling contractors, seismic companies, well services operators, subsea contractors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.75 × DR_USD − 0.5 × LC_local',
    formulaExplain: 'Hedge 75% of contracted USD day-rate revenues. Net against 50% of local currency cost hedges. OFS companies have natural hedges through local content requirements — netting reduces gross hedge notional.',
    rationale: 'OFS companies earn USD day-rates but incur costs in multiple local currencies. The natural hedge from local content obligations reduces net exposure. 75% confirmed ratio reflects typical backlog visibility in OFS contracting (6–12 months forward).',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.75, forecast: 0.50 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 250000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── HEALTHCARE / PHARMA — EXPANDED ──────────────────────────────────────────
  {
    id: 'cro-clinical-research',
    name: 'Clinical Research Organization (CRO)',
    shortName: 'CROO',
    description: 'Multi-currency clinical trial cost hedge for CROs managing global Phase II–IV studies with USD grant funding and multi-country site costs.',
    targetAudience: 'Contract research organizations, academic medical centers running industry-sponsored trials, CDMO operators',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.85 × G_USD − Σ(site_cost_local_i / spot_i)',
    formulaExplain: 'Hedge 85% of confirmed USD grant disbursements. Net against hedged local site cost payments across trial countries. Multi-currency netting reduces overall hedge notional significantly in multi-site trials.',
    rationale: 'CROs receive USD grants from pharma sponsors and pay site costs in EUR, GBP, BRL, MXN, INR and other currencies. Grant amounts are fixed; site costs vary by enrollment pace. 85% confirmed ratio reflects that grant disbursements are contractually defined but may be delayed by regulatory timelines.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.45 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'medical-device-oem',
    name: 'Medical Device OEM',
    shortName: 'MDEV',
    description: 'USD component import and EUR/JPY equipment cost hedge for medical device manufacturers with multi-currency supply chains.',
    targetAudience: 'Medical device manufacturers, diagnostic equipment companies, surgical robotics OEMs',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × BOM_USD + 0.70 × BOM_EUR',
    formulaExplain: 'Full hedge on USD-denominated bill-of-materials costs. 70% hedge on EUR and JPY components. Medical device supply chains are contract-locked 12–18 months in advance, enabling high confirmed coverage.',
    rationale: 'FDA-cleared devices have fixed bills of materials with regulatory-approved component sources. Switching to lower-cost alternatives to offset FX moves is often prohibited by 510(k) clearance conditions. Full BOM hedging protects margin on fixed-price device contracts without compromising regulatory compliance.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.70 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'hospital-group-treasury',
    name: 'Hospital Group Treasury',
    shortName: 'HOSP',
    description: 'USD medical equipment import and insurance receivable hedge for hospital groups with cross-border operations or USD-denominated imports.',
    targetAudience: 'Private hospital chains, hospital management companies, medical real estate operators',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × Equipment_AP_USD + 0.60 × Insurance_AR_USD',
    formulaExplain: 'Full hedge on USD medical equipment payables (MRI, CT, surgical systems). 60% hedge on USD insurance receivables from international patients. Equipment payables are committed at order; insurance receivables are subject to claim approval timelines.',
    rationale: 'Hospitals face asymmetric FX risk: equipment imports are committed costs while USD insurance revenue is variable. Full hedging of import payables is standard practice at investment-grade hospital groups. Partial hedging of insurance receivables reflects the timing uncertainty of claim settlement.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.60 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── TECHNOLOGY — EXPANDED ───────────────────────────────────────────────────
  {
    id: 'semiconductor-supply',
    name: 'Semiconductor Supply Chain',
    shortName: 'SEMI',
    description: 'Multi-currency wafer procurement and chip sales hedge for semiconductor companies with TSMC/UMC foundry exposure and global revenue.',
    targetAudience: 'Fabless semiconductor companies, IDMs, chip design houses, semiconductor distributors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.90 × Wafer_USD + 0.65 × Sales_EUR + 0.70 × Sales_KRW',
    formulaExplain: 'Hedge 90% of USD wafer purchase agreements (foundry commitments are binding 12 months forward). 65% of EUR chip sales. 70% of KRW exposure. The confirmed ratio on wafer costs is very high (foundry agreements are take-or-pay); revenue ratios reflect demand forecast uncertainty.',
    rationale: 'Semiconductor companies commit to foundry capacity 12–18 months in advance at USD prices (TSMC quotes in USD). Revenue is multi-currency across device OEM regions. The confirmed ratio on wafer costs is very high; revenue ratios reflect demand forecast uncertainty across end markets.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.90, forecast: 0.65 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'cloud-saas-enterprise',
    name: 'Enterprise SaaS / Cloud Revenue',
    shortName: 'CLUD',
    description: 'Large-scale USD ARR hedge for cloud software companies with global multi-currency revenue and USD-denominated infrastructure costs.',
    targetAudience: 'Enterprise SaaS companies, cloud infrastructure providers, platform companies with >$100M USD ARR',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.60 × ARR_USD + 0.40 × ARR_EUR + 0.30 × ARR_GBP',
    formulaExplain: 'Hedge 60% of USD annual recurring revenue (primary revenue stream), 40% of EUR ARR, and 30% of GBP ARR via rolling 6-month forwards. Lower ratios reflect the active currency alpha embedded in multi-currency SaaS pricing.',
    rationale: 'Large SaaS companies have natural hedges (USD infrastructure costs vs. USD revenue) but significant multi-currency revenue from European and APAC markets. 60% hedge ratio reflects standard practice at publicly traded SaaS companies that must manage EPS FX sensitivity for investor guidance.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.60, forecast: 0.40 },
      cost_assumptions: { spread_bps: 2.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'NONE',
  },
  {
    id: 'hardware-oem-import',
    name: 'Hardware OEM Importer',
    shortName: 'HDWR',
    description: 'USD hardware component import hedge for consumer electronics and IT hardware companies with Asia-sourced supply chains.',
    targetAudience: 'Consumer electronics importers, PC/server OEMs, IoT device manufacturers, component distributors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.90 × PO_AP_USD,  tenor = L/C_payment_terms',
    formulaExplain: 'Hedge 90% of placed purchase orders at letter-of-credit issuance. Tenor matches L/C payment terms (typically 30–120 days from shipment). 10% buffer for order amendments and returns.',
    rationale: 'Hardware companies commit to component purchases via L/C, creating a fixed USD payable at issuance. L/C terms (30–120 days) create a short, well-defined hedging window. 90% ratio reflects typical L/C amendment rate; hedging at L/C issuance is standard practice in consumer electronics treasury.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.90, forecast: 0.50 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── FINANCIAL — EXPANDED ────────────────────────────────────────────────────
  {
    id: 'fx-prime-broker',
    name: 'FX Prime Broker Overlay',
    shortName: 'FXPB',
    description: 'Residual FX exposure hedge for prime brokerage operations. Covers tail FX risk on client portfolio funding positions after client-level netting.',
    targetAudience: 'FX prime brokers, bank dealing desks, clearing members, tri-party custodians',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = VaR_99(ΣClient_FX) − δ_natural_net',
    formulaExplain: 'Hedge residual FX exposure equal to 99th percentile VaR of net client portfolio FX positions, minus the natural netting from offsetting client directions. Institutional interbank spreads only.',
    rationale: 'Prime brokers carry residual FX exposure from client portfolio funding after multi-currency netting. Regulatory capital requirements (CRR2/CRR3) treat un-hedged FX exposures on the banking book with specific capital charges. Hedging the 99th percentile residual minimizes regulatory capital consumption.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.99 },
      cost_assumptions: { spread_bps: 1.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'FAIR_VALUE',
  },
  {
    id: 'pension-ldi',
    name: 'Pension Fund — LDI FX Hedge',
    shortName: 'PNSN',
    description: 'Liability-driven FX hedge for defined benefit pension funds with overseas asset allocations. Neutralizes currency beta to focus on duration and credit risk.',
    targetAudience: 'DB pension funds, occupational pension schemes, superannuation funds, sovereign pension pools',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = w_fx × AUM_foreign,  w_fx ∈ [0.5, 1.0]',
    formulaExplain: 'Hedge w_fx fraction of foreign-currency asset allocation, where w_fx is set by the Investment Policy Statement. Standard DB fund practice: hedge 50–100% of FX in fixed income allocation; 0–50% in equity allocation.',
    rationale: 'DB pension funds are liability-matching by nature — liabilities are in local currency (member benefits) while assets may include significant foreign allocations. LDI frameworks prescribe full or near-full currency hedging on the fixed income overlay to preserve duration match. Equity FX is partially hedged based on mandate.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.50 },
      cost_assumptions: { spread_bps: 2.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'NET_INVESTMENT',
  },
  {
    id: 'university-endowment',
    name: 'University Endowment',
    shortName: 'UNIV',
    description: 'Return-preservation FX hedge for university endowments with diverse foreign asset allocations. Balances cost of hedging against risk of FX erosion to annual payout.',
    targetAudience: 'University endowments, foundation portfolios, charitable trusts, cultural institution endowments',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = 0.5 × w_bond_fx × AUM + 0.25 × w_equity_fx × AUM',
    formulaExplain: 'Hedge 50% of FX beta on foreign fixed income and 25% on foreign equity. Endowments spend ~5% annually; FX hedging cost must not exceed 0.5% of AUM or it erodes the spending rate.',
    rationale: 'University endowments have permanent capital goals and 5% annual spending rules. Foreign assets provide diversification but FX volatility can erode real returns in the reporting currency. Partial hedging (50% fixed income, 25% equity) is standard at investment-grade endowments, balancing hedge cost against FX risk reduction.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.50, forecast: 0.25 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 1000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'NET_INVESTMENT',
  },
  {
    id: 'reit-crossborder',
    name: 'REIT — Cross-Border Property',
    shortName: 'REITX',
    description: 'NOI and capital event FX hedge for REITs with international property portfolios. Protects USD/reporting currency distributions from overseas property income.',
    targetAudience: 'Listed REITs with international portfolios, private real estate funds, cross-border property investors',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 0.80 × NOI_fx + 1.0 × Debt_Repayment_fx',
    formulaExplain: 'Hedge 80% of foreign-currency net operating income (rental income less expenses) and 100% of FX-denominated debt service (principal and coupon). Lower ratio on NOI reflects vacancy and arrears uncertainty.',
    rationale: 'REIT distributions are directly linked to NOI; FX erosion of overseas property income reduces DPU (distribution per unit) and directly harms unitholders. Debt service hedging is 100% to protect covenant compliance. Standard practice at FTSE REIT index constituents with international exposure.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.50 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'ENHANCED',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'spv-structured',
    name: 'SPV / Structured Finance Vehicle',
    shortName: 'SPVX',
    description: 'Cash waterfall protection hedge for SPVs and securitization vehicles with cross-currency asset and liability stacks. Eliminates FX risk from the waterfall to protect senior note ratings.',
    targetAudience: 'CLO/CDO/ABS special purpose vehicles, project finance SPVs, export credit agency-guaranteed structures',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × Σ(FX_liability_i) − Σ(FX_asset_i)',
    formulaExplain: 'Full hedge of net FX exposure in the SPV waterfall (foreign currency liabilities minus foreign currency assets). Cross-currency swap for structural mismatches; NDF for near-term cash flow mismatches.',
    rationale: 'Rating agencies (S&P, Moody\'s) require SPVs to eliminate currency risk from rated tranches for investment-grade ratings. A cross-currency basis swap converting all note payments to the asset currency is the standard structured finance FX hedging technique.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.05 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── AGRICULTURE — EXPANDED ──────────────────────────────────────────────────
  {
    id: 'coffee-exporter',
    name: 'Coffee Exporter',
    shortName: 'COFF',
    description: 'USD export receipt hedge for green coffee exporters. Locks USD/local-currency conversion rate at forward contract for pre-committed sales.',
    targetAudience: 'Coffee cooperatives, green bean exporters, estate operators in Central America, Colombia, Brazil, Ethiopia',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.75 × E[Harvest_USD],  adjusted for ICE C arabica basis',
    formulaExplain: 'Hedge 75% of expected USD export revenue calculated as estimated harvest volume × forward ICE C price. Basis risk between physical coffee and ICE C futures creates residual exposure; hedge covers FX only, not commodity price.',
    rationale: 'Coffee cooperatives receive forward sales commitments from roasters (Nestlé, JAB, etc.) months before harvest. Locking the FX rate on committed sales volumes provides cash flow certainty for smallholder payments. 75% ratio accommodates yield uncertainty from weather events and quality rejections.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.75 },
      cost_assumptions: { spread_bps: 7.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'cocoa-chocolate',
    name: 'Cocoa / Chocolate Supply Chain',
    shortName: 'COCO',
    description: 'USD cocoa procurement and chocolate export hedge for confectionery companies and cocoa traders. Manages dual commodity and FX exposure.',
    targetAudience: 'Chocolate manufacturers, cocoa grinders, confectionery exporters, origin traders in West Africa',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.70 × USD_Procurement + 0.50 × EUR_Sales',
    formulaExplain: 'Hedge 70% of USD cocoa procurement costs (ICE London-priced) and 50% of EUR chocolate sales. Separate hedges for procurement (USD) and sales (EUR/GBP) to avoid double-hedging natural cross-currency flows.',
    rationale: 'Cocoa is priced in USD on ICE London and ICE New York. Chocolate is sold in EUR/GBP to European confectionery markets. Dual-currency exposure creates complex natural hedges. Separate hedges by flow direction prevent over-hedging while protecting margin on both sides.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.70, forecast: 0.50 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'grain-trader',
    name: 'Grain / Oilseed Trader',
    shortName: 'GRNT',
    description: 'Back-to-back USD grain procurement and export sale FX hedge. Locks the FX spread on physical grain trading books.',
    targetAudience: 'Agricultural trading houses, grain merchants, origination desks at agribusiness companies',
    riskPosture: 'AGGRESSIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × (Sale_USD − Purchase_USD) = Net_FX_Spread',
    formulaExplain: 'Full hedge of net USD FX exposure on matched physical grain trades (sale price minus purchase price, both in USD, converted to local currency cash flow). Trading books aim for zero open FX on matched books.',
    rationale: 'Physical grain traders operate on thin margins (0.5–2% of notional). Any unhedged FX exposure can eliminate the entire trading margin. Back-to-back FX hedging on matched physical trades is standard at major commodity merchants (ADM, Bunge, Cargill). 100% confirmed ratio reflects back-to-back physical commitments.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.80 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'SHORT',
    governance_tier: 'ENHANCED',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'livestock-meat-export',
    name: 'Livestock / Meat Packing Export',
    shortName: 'MEAT',
    description: 'USD beef and poultry export receipt hedge for meat packers and protein exporters with seasonal slaughter cycles.',
    targetAudience: 'Beef and poultry processors, cold storage exporters, cooperatives with protein export operations',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.80 × Q_slaughter × P_USD_FOB',
    formulaExplain: 'Hedge 80% of expected USD free-on-board export revenue based on seasonal slaughter volume and forward USD protein prices. 20% buffer for weight variation, quality downgrade, and export market access risk.',
    rationale: 'Meat processing companies purchase cattle/poultry in local currency and sell protein in USD. Slaughter volumes are committed months in advance based on feedlot populations. 80% ratio reflects typical volume certainty at the time of hedge initiation, with buffer for yield and grade variation.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.60 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'STANDARD',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },

  // ─── SOVEREIGN — EXPANDED ────────────────────────────────────────────────────
  {
    id: 'development-bank',
    name: 'Development Bank Project Loan',
    shortName: 'DEVB',
    description: 'USD/EUR disbursement and local currency repayment hedge for multilateral development banks and development finance institutions.',
    targetAudience: 'Multilateral development banks (MDB), development finance institutions (DFI), export credit agencies (ECA)',
    riskPosture: 'CONSERVATIVE',
    category: 'SOVEREIGN',
    formula: 'H = 1.0 × Disbursement_USD + Σ(Repayment_Schedule_LC / spot_fwd)',
    formulaExplain: 'Full hedge on project loan disbursements from USD/EUR lending currency to local currency at disbursement date. Forward hedge on each scheduled local currency repayment to lock USD/EUR recovery amount.',
    rationale: 'Development banks lend in hard currencies (USD, EUR) and receive local currency repayments. Without hedging, local currency depreciation reduces the USD/EUR value of recovering the principal. Most MDBs (IFC, IADB, AfDB) hedge individual project loan FX exposures through their TCX partnerships or proprietary swap programs.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.20 },
      cost_assumptions: { spread_bps: 2.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 10000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'sovereign-wealth-fund',
    name: 'Sovereign Wealth Fund (SWF)',
    shortName: 'SWFD',
    description: 'Strategic FX overlay for sovereign wealth funds with foreign asset allocations. Manages currency beta independently from asset allocation decisions.',
    targetAudience: 'Sovereign wealth funds, national reserve funds, intergenerational savings funds',
    riskPosture: 'MODERATE',
    category: 'SOVEREIGN',
    formula: 'H = β_target × AUM_foreign,  β_target ∈ [0.3, 0.7]',
    formulaExplain: 'Maintain currency beta (β_target) on foreign asset portfolio. β_target of 0.5 = hedge 50% of FX exposure. Range 30–70% reflects SWF mandates that typically allow currency as an active return source while limiting drawdown from unhedged FX moves.',
    rationale: 'SWFs with stabilization mandates hedge more aggressively. SWFs with savings/intergenerational mandates (GIC Singapore, NBIM Norway) often maintain partial currency hedges or currency overlays as active return strategies. This preset covers the moderate case with a 50% beta target.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.50, forecast: 0.30 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'NET_INVESTMENT',
  },
  {
    id: 'municipal-debt-service',
    name: 'Municipal Government Debt Service',
    shortName: 'MUNI',
    description: 'USD-denominated bond coupon and principal hedge for municipal governments and sub-sovereign entities with foreign currency debt.',
    targetAudience: 'State governments, municipal authorities, public utility commissions, sub-sovereign borrowers',
    riskPosture: 'CONSERVATIVE',
    category: 'SOVEREIGN',
    formula: 'H = 1.0 × (Coupon_USD + Principal_USD),  match maturity to bond schedule',
    formulaExplain: 'Full hedge on every USD coupon payment and principal repayment date over the bond life. Forward contracts or cross-currency swaps matched to bond payment schedule. Local tax revenue is the hedge item.',
    rationale: 'Municipal governments with USD bonds must convert local tax revenue at each coupon and principal date. A 20% local currency depreciation against USD can increase annual debt service cost by 20% of the bond outstanding. Full hedging converts the debt service obligation to a fixed local currency amount, enabling budget certainty.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.00 },
      cost_assumptions: { spread_bps: 2.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 2000000,
    },
    maturity_profile: 'LONG',
    governance_tier: 'COMMITTEE',
    evidence_grade: 'AUDITED',
    accounting_mode: 'NONE',
  },

  // ─── EMERGING MARKET SPECIALIZATION ──────────────────────────────────────────
  {
    id: 'brazil-brl-corporate',
    name: 'Brazil BRL Corporate Hedger',
    shortName: 'BRLC',
    description: 'BRL-specialized corporate hedge policy for USD/BRL exposure. Calibrated to BRL structural volatility, NDF-only settlement, and BACEN-regulated derivatives market conventions.',
    targetAudience: 'Brazilian corporates, multinationals with BRL exposure, importers/exporters with USD/BRL flows',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.80 × CF_USD + 0.55 × FF_USD,  settlement = PTAX fixing',
    formulaExplain: 'Hedge 80% of confirmed and 55% of forecast USD flows, settled at the BACEN PTAX official fixing rate. Higher spread assumption reflects BRL NDF market depth and cupom cambial (Brazil forward premium) structure.',
    rationale: 'BRL is among the most volatile major EM currencies (historical realized vol: 15–25% annualized). All USD/BRL forwards settle as NDFs via the PTAX official rate published by BACEN. The cupom cambial is driven by Brazil domestic interest rates, which can spike to 400+ bps above USD rates in risk-off periods, making long-dated hedging expensive.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.55 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 50000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'mexico-mxn-nearshore',
    name: 'Mexico MXN Nearshore (Maquiladora)',
    shortName: 'MXNN',
    description: 'MXN-optimized policy for nearshore manufacturing and maquiladora operations. Accounts for MXN liquidity depth, TIIE-linked forward premium, and US-MX trade flow patterns.',
    targetAudience: 'Maquiladoras, nearshore manufacturers, IMMEX program operators, auto Tier-1 suppliers in Mexico',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 1.0 × AP_USD + 0.70 × AR_USD − 0.90 × NaturalHedge_MXN',
    formulaExplain: 'Full hedge on USD payables (imported materials). 70% hedge on USD receivables (US OEM payments). Natural hedge credit: 90% of MXN labor/overhead costs offset against USD revenues before hedging.',
    rationale: 'Maquiladora operations have a structural natural hedge: MXN depreciation reduces USD cost of labor (their largest input) while maintaining USD revenue. Netting the natural hedge before hedging dramatically reduces hedge cost and avoids over-hedging the natural position. TIIE-linked forward premiums make MXN forwards modestly cheaper than other EM pairs.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.00, forecast: 0.70 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'turkey-try-corporate',
    name: 'Turkey TRY High-Carry Hedger',
    shortName: 'TRYC',
    description: 'TRY-specialized hedge policy for USD/TRY exposure. Calibrated to extreme carry costs (400–2000 bps forward premium), high vol (30–50% realized), and NDF-only settlement post-2020.',
    targetAudience: 'Turkish corporates with USD debt, importers in Turkey, multinationals with TRY operations',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 0.85 × CF_confirmed,  FF = 0.25 (carry cost prohibits forecast hedging)',
    formulaExplain: 'Hedge 85% of confirmed USD flows. Forecast ratio is deliberately low (25%) because TRY forward premiums of 400–2000 bps make forecast hedging extremely expensive. Confirmed-flow-only hedging is the dominant market practice for TRY.',
    rationale: 'USD/TRY forward costs have exceeded 2000 bps annually during periods of TCMB policy uncertainty (2021–2023). At these levels, hedging 100% of forecast flows would cost 20% of notional per year in carry alone, potentially exceeding the economic benefit. Turkish corporates must hedge confirmed debt service while accepting forecast flow exposure.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.25 },
      cost_assumptions: { spread_bps: 15.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'south-africa-zar-resources',
    name: 'South Africa ZAR Resources Exporter',
    shortName: 'ZARR',
    description: 'ZAR-optimized policy for South African mining and resources exporters. Accounts for ZAR-commodity correlation, load-shedding operational risk, and JSE-linked forward premium structure.',
    targetAudience: 'South African gold/platinum/coal miners, resources exporters, JSE-listed commodity producers',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.75 × Q_production × P_USD_commodity',
    formulaExplain: 'Hedge 75% of estimated USD commodity export revenue. ZAR/USD has a negative correlation with commodity prices (ZAR appreciates when commodity prices rise), which provides partial natural hedge. Hedge ratio lower than generic commodity exporters to reflect this correlation benefit.',
    rationale: 'ZAR is a commodity currency: ZAR appreciates when gold and platinum prices rise, partially offsetting the FX revenue effect. A gold miner that fully hedges both commodity price and ZAR/USD eliminates all upside. The 75% hedge ratio retains the ZAR-commodity correlation benefit while protecting the operational floor rate required for JSE analyst guidance.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.75, forecast: 0.55 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
  {
    id: 'india-inr-tech-services',
    name: 'India INR Technology & IT Services',
    shortName: 'INRT',
    description: 'INR-optimized hedge policy for Indian IT services and technology exporters. Calibrated to RBI intervention behavior, forward premium structure, and USD/INR NDF market conventions.',
    targetAudience: 'Indian IT services companies (TCS, Infosys model), BPO operators, technology exporters, GCC operators in India',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.65 × AR_USD + 0.40 × FF_quarterly',
    formulaExplain: 'Hedge 65% of confirmed USD IT services receivables via RBI-compliant forward contracts. 40% coverage of quarterly forecast revenue. RBI guidelines require Indian exporters to hedge within specified bands; excess hedging requires special dispensation.',
    rationale: 'Indian IT exporters earn USD revenue and pay INR salaries (their largest cost). USD/INR has shown RBI-managed volatility (realized vol 4–6% vs. free-float EM peers at 10–25%). RBI allows exporters to hedge up to 100% of firm commitments but restricts speculative hedging. 65% confirmed / 40% forecast reflects compliance with FEMA export hedging guidelines.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.65, forecast: 0.40 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
    maturity_profile: 'MEDIUM',
    governance_tier: 'ENHANCED',
    evidence_grade: 'DOCUMENTED',
    accounting_mode: 'CASH_FLOW_HEDGE',
  },
];

// Category metadata for UI grouping
export const PRESET_CATEGORIES: {
  id: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  label: string;
  description: string;
}[] = [
  { id: 'CORPORATE', label: 'Corporate',      description: 'General corporate treasury policies' },
  { id: 'FINANCIAL', label: 'Financial',       description: 'Banks, funds, and financial institutions' },
  { id: 'SOVEREIGN', label: 'Sovereign / SOE', description: 'Government and state-owned enterprises' },
  { id: 'SECTOR',    label: 'Sector-Specific', description: 'Industry-tailored hedge strategies' },
];
