import type { PolicyConfig } from '../api/types';

export interface PolicyPreset {
  id: string;
  name: string;
  shortName: string;
  description: string;
  targetAudience: string;
  riskPosture: 'CONSERVATIVE' | 'MODERATE' | 'AGGRESSIVE';
  category: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  formula: string;           // display formula for tooltip
  formulaExplain: string;    // plain-English explanation of the formula
  rationale: string;         // why this preset exists / real-world use
  policy: PolicyConfig;
}

export const POLICY_PRESETS: PolicyPreset[] = [
  // ─── SME / STARTUP ──────────────────────────────────────────────────────────
  {
    id: 'small-business',
    name: 'Small Business / Startup',
    shortName: 'SME',
    description: 'No minimum trade size — every bucket executes regardless of notional. Built for SMEs, startups, and early-stage hedgers with smaller transaction volumes.',
    targetAudience: 'SMEs, startups, freelancers, small importers/exporters with sub-$500K exposures',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.5 × FF,  min = $0',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows + 50% of Forecast Flows. No minimum trade size filter — every bucket executes even at very small notionals. Avoids the suppression issue small businesses face with standard corporate presets.',
    rationale: 'Standard corporate presets set minimum trade sizes ($25k–$500k) to avoid bank execution costs on tiny tickets. For SMEs hedging their first transactions, this suppresses all buckets. Setting min = $0 lets every exposure get a hedge ticket, regardless of size.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.80, forecast: 0.50 },
      cost_assumptions: { spread_bps: 25 },
      execution_product: 'NDF',
      min_trade_size_usd: 0,
    },
  },

  // ─── CORPORATE ──────────────────────────────────────────────────────────────
  {
    id: 'full-protection',
    name: 'Full Protection',
    shortName: 'FULL',
    description: 'Maximum hedge coverage for all confirmed and forecast flows. Zero FX tolerance.',
    targetAudience: 'Import-dependent manufacturers, regulated utilities, fixed-price contracts',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 1.0 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 100% of Forecast Flows. Eliminates all open FX risk on the balance sheet.',
    rationale: 'Used by companies with fixed-price customer contracts in USD where any FX move directly erodes margin. Common in aerospace supply chains and infrastructure projects.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 1.0 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
  },
  {
    id: 'conservative-treasury',
    name: 'Conservative Treasury',
    shortName: 'CNSV',
    description: 'Full confirmed coverage, minimal forecast hedging. Board-mandated treasury policy.',
    targetAudience: 'Investment-grade corporates, regulated entities, public companies',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.25 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 25% of Forecast Flows. Protects firm commitments fully; accepts limited forecast variance.',
    rationale: 'Standard for CFO-mandated policies at listed companies. Board approves 25% forecast ratio to avoid over-hedging speculative pipelines while locking confirmed A/P.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.25 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 100000,
    },
  },
  {
    id: 'balanced-corporate',
    name: 'Balanced Corporate',
    shortName: 'BLNC',
    description: 'Full confirmed coverage, moderate forecast hedging. Standard mid-market FX program.',
    targetAudience: 'Mid-market corporates, manufacturing, distribution',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.5 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 50% of Forecast Flows. Balances cost certainty with forecast participation.',
    rationale: 'The most common treasury policy globally. Hedges all firm orders while covering half the pipeline, reflecting typical 50–60% forecast accuracy in mid-market.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.5 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 50000,
    },
  },
  {
    id: 'active-risk-mgmt',
    name: 'Active Risk Management',
    shortName: 'ACTV',
    description: 'High coverage across confirmed and forecast flows. Active FX risk mandate with tactical overlay.',
    targetAudience: 'Large corporates, frequent hedgers, treasury centres',
    riskPosture: 'AGGRESSIVE',
    category: 'CORPORATE',
    formula: 'H = 1.0 × CF + 0.75 × FF',
    formulaExplain: 'Hedge Notional = 100% of Confirmed Flows + 75% of Forecast Flows. High forecast ratio reflects strong pipeline visibility and active risk mandate.',
    rationale: 'Used by corporates with high forecast accuracy (>80%) and treasury teams empowered to run active FX books. Typical in automotive and consumer goods multinationals.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.75 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 25000,
    },
  },
  {
    id: 'cost-sensitive',
    name: 'Cost-Sensitive Hedger',
    shortName: 'COST',
    description: 'Confirmed-only coverage. Hedges firm commitments only — avoids forecast hedging cost.',
    targetAudience: 'SMEs, cost-constrained treasuries, seasonal businesses',
    riskPosture: 'CONSERVATIVE',
    category: 'CORPORATE',
    formula: 'H = 0.8 × CF + 0.0 × FF',
    formulaExplain: 'Hedge Notional = 80% of Confirmed Flows only. No forecast hedging. Slight under-hedge on confirmed to accommodate minor amendments without unwind cost.',
    rationale: 'Common in SMEs where treasury resources are limited. 80% confirmed ratio accounts for typical 5–20% contract amendment rate, avoiding costly unwind of over-hedged positions.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.8, forecast: 0.0 },
      cost_assumptions: { spread_bps: 8.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 75000,
    },
  },
  {
    id: 'layered-rolling',
    name: 'Layered Rolling',
    shortName: 'LAYR',
    description: 'Graduated hedge build-up over 12 months. Avoids locking full exposure at a single spot rate.',
    targetAudience: 'Exporters, commodity traders, businesses with rolling 12-month pipelines',
    riskPosture: 'MODERATE',
    category: 'CORPORATE',
    formula: 'H_t = CF_t + (1 - t/T) × FF_t',
    formulaExplain: 'Near-term confirmed flows hedged 100%. Forecast ratio declines with horizon: near-term at 60%, far-term at lower coverage. Achieves time-weighted average rate across the hedging window.',
    rationale: 'Prevents rate concentration risk. A company that hedges at the same time each year risks adverse timing. Layering achieves an average rate across the full hedging window.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.6 },
      cost_assumptions: { spread_bps: 4.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 50000,
    },
  },

  // ─── FINANCIAL ──────────────────────────────────────────────────────────────
  {
    id: 'bank-trading-book',
    name: 'Bank Trading Book',
    shortName: 'BANK',
    description: 'Tight spread, high minimum, NDF-only. Mirrors interbank desk execution parameters.',
    targetAudience: 'Bank subsidiaries, financial institutions, proprietary trading desks',
    riskPosture: 'AGGRESSIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF + 0.9 × FF, spread ≤ 2 bps',
    formulaExplain: 'Near-full coverage with interbank spread assumptions. 90% forecast ratio reflects high-confidence flow desks. Spread at 2 bps = wholesale institutional pricing tier.',
    rationale: 'Financial institutions hedge near-100% to maintain clean accounting books. The 2 bps spread reflects actual interbank cost, not retail FX mark-up.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.9 },
      cost_assumptions: { spread_bps: 2.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 500000,
    },
  },
  {
    id: 'asset-manager',
    name: 'Asset Manager',
    shortName: 'AMGR',
    description: 'Benchmark-relative hedging. Partial confirmed hedge, minimal forecast. Tracks mandate benchmark.',
    targetAudience: 'Fund managers, pension funds, sovereign wealth funds',
    riskPosture: 'MODERATE',
    category: 'FINANCIAL',
    formula: 'H = β × CF,  β ∈ [0.5, 1.0]',
    formulaExplain: 'Hedge ratio β is set by the investment mandate benchmark. Typically 50–75% of confirmed flows. Forecast flows not hedged — treated as active currency alpha opportunity.',
    rationale: 'Most fund mandates specify a currency hedge ratio (e.g., 50% benchmark hedge). Forecast flows are left open as active currency views are part of the return profile.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.75, forecast: 0.0 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 250000,
    },
  },
  {
    id: 'private-equity',
    name: 'Private Equity',
    shortName: 'PE',
    description: 'Exit-date hedging. Protects terminal valuation and IRR, not operating flows.',
    targetAudience: 'PE funds, M&A teams, cross-border acquisition financing',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × CF_exit,  tenor = T_exit',
    formulaExplain: 'Full hedge on exit proceeds only via single long-dated forward locked at acquisition date. Tenor matches expected hold period. Protects USD IRR from FX drift over the hold.',
    rationale: 'PE investors care about USD-denominated IRR. A 10% FX move over a 5-year hold period destroys a full year of value creation. Exit-date forward locks the conversion rate.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.1 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 1000000,
    },
  },
  {
    id: 'insurance-reserves',
    name: 'Insurance Reserves',
    shortName: 'INSR',
    description: 'Liability-matching hedge. Matches reserve currency to claims currency. Solvency II aligned.',
    targetAudience: 'Insurance companies, reinsurers, annuity providers',
    riskPosture: 'CONSERVATIVE',
    category: 'FINANCIAL',
    formula: 'H = 1.0 × L_fx,  L_fx = FX-denominated liabilities',
    formulaExplain: 'Hedge notional = 100% of FX-denominated reserve liabilities. Confirmed-only hedging. Forecast claims provisioned via actuarial buffer, not FX forwards.',
    rationale: 'Regulators require insurers to match asset and liability currencies. A currency mismatch creates solvency ratio volatility that can trigger regulatory intervention.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.15 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 500000,
    },
  },

  // ─── SOVEREIGN ──────────────────────────────────────────────────────────────
  {
    id: 'sovereign-debt-service',
    name: 'Sovereign Debt Service',
    shortName: 'SOVR',
    description: 'Full USD debt service hedging. Protects sovereign budget from FX-driven debt cost spikes.',
    targetAudience: 'Government treasuries, public sector entities, development banks',
    riskPosture: 'CONSERVATIVE',
    category: 'SOVEREIGN',
    formula: 'H = 1.0 × D_USD,  D_USD = annual USD debt coupon + principal',
    formulaExplain: 'Full hedge on all USD-denominated debt service (principal + coupon). No forecast hedging of revenue — those flow through the annual budget process separately.',
    rationale: 'A 15% MXN depreciation can add 1–2% of GDP to sovereign debt service costs. Governments with USD bonds hedge coupon/principal flows to protect fiscal space and credit ratings.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.0 },
      cost_assumptions: { spread_bps: 2.5 },
      execution_product: 'FWD',
      min_trade_size_usd: 5000000,
    },
  },
  {
    id: 'export-proceeds',
    name: 'Export Proceeds',
    shortName: 'XPRT',
    description: 'Commodity export receipts hedging. Locks USD revenue against local currency depreciation.',
    targetAudience: 'State-owned commodity exporters, mining companies, oil & gas NOCs',
    riskPosture: 'MODERATE',
    category: 'SOVEREIGN',
    formula: 'H = 0.6 × Q × P_fwd',
    formulaExplain: '60% of expected export revenue hedged: volume (Q) from production forecast × forward commodity price (P_fwd). 40% left open for commodity price upside.',
    rationale: 'PEMEX, Codelco, and similar SOEs hedge 50–70% of expected receipts. Full hedging sacrifices commodity upside; zero hedging exposes the national budget to commodity AND FX shocks simultaneously.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.6 },
      cost_assumptions: { spread_bps: 3.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 2000000,
    },
  },
  {
    id: 'central-bank-reserves',
    name: 'Central Bank FX Ops',
    shortName: 'CBNK',
    description: 'Reserve management overlay. Minimal hedging — intervention-ready liquidity maintained.',
    targetAudience: 'Central banks, monetary authorities, FX reserve managers',
    riskPosture: 'AGGRESSIVE',
    category: 'SOVEREIGN',
    formula: 'H = min(0.1 × R, VaR_limit)',
    formulaExplain: 'Hedge no more than 10% of reserves or the VaR daily limit, whichever is smaller. Reserves must remain deployable for market intervention — hedging constrains liquidity.',
    rationale: 'Central banks rarely hedge reserves as they need FX liquidity for market interventions. When they do hedge, it is marginal overlays only. This preset captures that operational reality.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.1, forecast: 0.0 },
      cost_assumptions: { spread_bps: 1.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000000,
    },
  },

  // ─── SECTOR-SPECIFIC ────────────────────────────────────────────────────────
  {
    id: 'airline-fuel',
    name: 'Airline / Aviation',
    shortName: 'AIRL',
    description: 'Jet fuel cost + USD revenue hedge. Covers fuel payables and USD-denominated ticket revenue.',
    targetAudience: 'Airlines, charter operators, aviation lessors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H_fuel = 0.7 × Q_fuel × P_jet;  H_rev = 0.5 × USD_rev',
    formulaExplain: 'Fuel payables: hedge 70% of projected fuel volume at forward jet fuel price. USD revenue: hedge 50% of forecast USD ticket sales to protect MXN revenue floor.',
    rationale: 'IATA recommends 50–70% fuel cost hedging for airlines. Most LatAm carriers (Aeromexico, Avianca) hedge fuel and USD revenue separately to manage both cost and revenue FX legs.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 100000,
    },
  },
  {
    id: 'tech-saas',
    name: 'Technology / SaaS',
    shortName: 'TECH',
    description: 'USD revenue, MXN cost base. Light hedge on USD receivables — preserves natural hedge benefit.',
    targetAudience: 'SaaS companies, technology exporters, nearshore services',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.5 × ARR_USD (6-month rolling)',
    formulaExplain: 'Hedge 50% of Annual Recurring Revenue via 6-month rolling forwards. Remaining 50% benefits from MXN depreciation (natural cost-base hedge). Balances floor protection with upside.',
    rationale: 'Tech companies with USD revenue and MXN cost bases have a natural hedge — MXN depreciation expands margins. Hedging half the USD revenue locks a floor without sacrificing the natural hedge benefit.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.5, forecast: 0.3 },
      cost_assumptions: { spread_bps: 5.0 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },
  {
    id: 'real-estate-dev',
    name: 'Real Estate / REIB',
    shortName: 'REIT',
    description: 'USD construction cost hedge by project phase. Protects import material payables.',
    targetAudience: 'Real estate developers, construction groups, hotel chains',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × Import_AP (per project phase)',
    formulaExplain: 'Full hedge on confirmed USD import payables (steel, equipment, FF&E). Phased by project milestone. Forecast exposure from future phases left open pending permits and design approval.',
    rationale: 'Real estate projects have fixed USD import costs (elevators, HVAC, finishes) priced at contract award. Any FX move after contract locks in a loss. Full hedge on confirmed AP is industry standard.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.2 },
      cost_assumptions: { spread_bps: 6.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 200000,
    },
  },
  {
    id: 'pharma-import',
    name: 'Pharma / Healthcare',
    shortName: 'PHRM',
    description: 'API and equipment USD import hedging. Regulatory margin protection for essential medicines.',
    targetAudience: 'Pharmaceutical importers, hospital groups, medical device distributors',
    riskPosture: 'CONSERVATIVE',
    category: 'SECTOR',
    formula: 'H = min(1.0 × CF,  regulatory_price_cap / spot)',
    formulaExplain: 'Full hedge on confirmed API import payables, subject to regulatory price cap. If FX move would breach the COFEPRIS price threshold, the hedge notional is capped at the breakeven.',
    rationale: 'Pharma companies in MX operate under price controls. A 20% FX move on active pharmaceutical ingredients (APIs) cannot be passed to patients — it destroys operating margins entirely.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.4 },
      cost_assumptions: { spread_bps: 4.0 },
      execution_product: 'FWD',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'agri-commodity',
    name: 'Agriculture / Commodity',
    shortName: 'AGRI',
    description: 'Harvest-season USD receipt hedging. Locks exchange rate at planting for harvest proceeds.',
    targetAudience: 'Agribusiness, grain traders, commodity exporters, cooperatives',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.7 × E[Harvest_USD],  σ_volume = 0.15',
    formulaExplain: '70% of expected harvest USD proceeds hedged at planting (6 months forward). Volume uncertainty buffer of 15% — actual harvest may vary. Excess or deficit rolls to next season.',
    rationale: 'Farmers lock a floor rate at planting. 100% hedging is impossible as harvest volume is uncertain. 70% = expected minimum harvest at 1σ confidence, protecting downside without over-hedging.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.85, forecast: 0.7 },
      cost_assumptions: { spread_bps: 5.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 10000,
    },
  },
  {
    id: 'auto-supply-chain',
    name: 'Automotive Supply Chain',
    shortName: 'AUTO',
    description: 'Tier-1/2 supplier policy. Full USD component cost hedge with receivable netting.',
    targetAudience: 'Auto parts manufacturers, Tier-1/2 suppliers, maquiladoras',
    riskPosture: 'AGGRESSIVE',
    category: 'SECTOR',
    formula: 'H = 1.0 × AP_USD − 0.8 × AR_USD (net exposure)',
    formulaExplain: 'Net hedge = Fully hedge USD payables (raw materials) minus 80% of USD receivables (OEM invoices). Netting payables against receivables reduces hedge cost by 60–70% vs. gross hedging.',
    rationale: 'Auto suppliers buy USD-denominated steel and sell to USD-paying OEMs. The natural hedge is high but imperfect due to JIT timing mismatches. Netting dramatically reduces FX hedge cost.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 1.0, forecast: 0.8 },
      cost_assumptions: { spread_bps: 3.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },
  {
    id: 'retail-importer',
    name: 'Retail Importer',
    shortName: 'RETL',
    description: 'Seasonal inventory hedge. Locks USD purchase cost for holiday season buying windows.',
    targetAudience: 'Retailers, e-commerce importers, consumer goods distributors',
    riskPosture: 'MODERATE',
    category: 'SECTOR',
    formula: 'H = 0.9 × PO_USD,  tenor = payment_terms',
    formulaExplain: '90% of placed purchase orders hedged at order date. 10% buffer for cancellations and returns. Hedge tenor matches ocean freight + payment terms (typically 60–120 days).',
    rationale: 'A retailer placing holiday orders in July faces a December payment. A 10% FX move between order and payment dates destroys the margin on that inventory. Hedge at PO date locks COGS.',
    policy: {
      bucket_mode: 'CALENDAR_MONTH',
      hedge_ratios: { confirmed: 0.9, forecast: 0.4 },
      cost_assumptions: { spread_bps: 6.5 },
      execution_product: 'NDF',
      min_trade_size_usd: 5000,
    },
  },
];

// Category metadata for UI grouping
export const PRESET_CATEGORIES: {
  id: 'CORPORATE' | 'FINANCIAL' | 'SOVEREIGN' | 'SECTOR';
  label: string;
  description: string;
}[] = [
  { id: 'CORPORATE', label: 'Corporate',      description: 'General corporate treasury policies' },
  { id: 'FINANCIAL', label: 'Financial',       description: 'Banks, funds, and financial institutions' },
  { id: 'SOVEREIGN', label: 'Sovereign / SOE', description: 'Government and state-owned enterprises' },
  { id: 'SECTOR',    label: 'Sector-Specific', description: 'Industry-tailored hedge strategies' },
];
