"""include auth_audit_logs (correct Base)

Revision ID: 3450c02f9c01
Revises: 5c5766647faa
Create Date: 2025-10-08 03:41:52.159794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3450c02f9c01'
down_revision: Union[str, Sequence[str], None] = '5c5766647faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAIL', 'REGISTER_SUCCESS', 'REGISTER_FAIL', 'REFRESH_SUCCESS', 'REFRESH_FAIL', 'LOGOUT', name='auth_event_type'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAIL', name='auth_event_status'), nullable=False),
    sa.Column('reason_code', sa.Enum('OK', 'EMAIL_ALREADY_EXISTS', 'EMAIL_NOT_FOUND', 'INVALID_PASSWORD', 'ACCOUNT_DISABLED', 'TOKEN_EXPIRED', 'TOKEN_REVOKED', 'TOKEN_INVALID', 'ROTATION_REVOKED_PREVIOUS', 'SERVER_ERROR', name='auth_reason_code'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_audit_logs_created_at'), 'auth_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_auth_audit_logs_event_created_at', 'auth_audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_event_type'), 'auth_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_request_id'), 'auth_audit_logs', ['request_id'], unique=False)
    op.create_index('ix_auth_audit_logs_user_created_at', 'auth_audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_auth_audit_logs_user_id'), 'auth_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_audit_logs_user_id'), table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_logs_user_created_at', table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_request_id'), table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_event_type'), table_name='auth_audit_logs')
    op.drop_index('ix_auth_audit_logs_event_created_at', table_name='auth_audit_logs')
    op.drop_index(op.f('ix_auth_audit_logs_created_at'), table_name='auth_audit_logs')
    op.drop_table('auth_audit_logs')
    # ### end Alembic commands ###
